
public enum ProxyName
{
    CfgLanguageProxy,
    CfgSpacecraftProxy,
    CfgMapListProxy,
    CfgCollectObjectListProxy,
    CfgMapMissionListProxy,
    CfgWorldMissionProxy,
    CfgNpcTriggerProxy,
    CfgStateAnimationProxy,
    CfgPveProxy,
    CfgRewardListProxy,
    CfgShipLevelProxy,
    CfgShipLevelExpProxy,
    CfgAttributeProxy,
    CfgSpacecraftElementProxy,
    CfgSpacecraftGearProxy,
    CfgSubMissionProxy,
    CfgTemporaryChestListProxy,
    CfgTimelineListProxy,
    CfgBattleListProxy,
    CfgLeapListProxy,
    TeleportListProxy,
    CfgDailyTaskProxy,
    CfgMapNpcListProxy,
    CfgSettingProxy,
    CfgAudioListProxy,
    CfgEscConfigProxy,
    PackagePosMoneyProxy,
    CfgMissionListProxy,
    CfgAttributeListProxy,
    CfgSceneEventProxy,
    CfgNpcInteractiveListProxy,
    CfgDungeonProxy,
    CfgHotKeyProxy,
    CfgSkillFxPostProxy,
    CfgSkillFxPrefabProxy,
    CfgSkillFxProxy,
    CfgSkillFxShakeProxy,
    CfgTeleportListProxy,
    CfgMissionNpcListProxy,
    CfgNpcListProxy,
    CfgItemListProxy,
    CfgPackagePosMoneyProxy,

    ItemListProxy,

    CfgUITipsProxy,

    LoginProxy,
    ServerListProxy,
    SceneProxy,
	/// <summary>
	/// 主角技能信息
	/// </summary>
	PlayerSkillProxy,
	PlayerProxy,
    DungeonMissionProxy,
    WorldMissionProxy,
    SceneEventProxy,
    /// <summary>
    /// 生产Proxy
    /// </summary>
    FoundryProxy,
    DiyProxy,
    PackageProxy,
    ShipProxy,
    MailProxy,
    LogProxy,
    FriendProxy,
    MissionProxy,
    MissionTrackProxy,
    TeamProxy,
    ChatProxy,
    ShopProxy,
    CfgClientMapNpcProxy,
    CfgSkillSystemProxy,
	CfgSkillSystemGrowProxy,
	CfgSkillSystemPathProxy,
	CfgSkillSystemFxProxy,
	CfgSkillSystemEffectProxy,
	CfgSkillSystemBuffPassiveProxy,
	TeamPlatformProxy,
    PveProxy,
    SelectTargetProxy,
    GameLocalizationProxy,

    CfgIconProxy,
    CfgEternityProxy,
    CfgMailProxy,
	FriendAddProxy,
	StoreHelperProxy,
    GameplayProxy,
    TaskProxy,
    TaskTrackingProxy,
    MSAIBossProxy,
	TreasureHuntProxy,
	CfgStarmapProxy,
	ShipItemsProxy,
	SceneShipProxy,
	RaycastProxy,
	AutoNavigationProxy,
	TalentProxy,
	Total,
}