/*
compile by protobuf, please don't edit it manually. 
Any problem please contact tongxuehu@gmail.com, thx.
*/

using System;
using System.Collections.Generic;
using System.IO;
using Assets.Scripts.Lib.Net;

namespace Assets.Scripts.Define
{
	public enum ClientPingInterval
	{
		PingIntervalTime = 2,
	}

	public enum KSceneObjectType
	{
		sotInvalid = 0,
		sotHero = 1,
		sotDoodad = 2,
		sotEffect = 3,
		sotMonsterGroup = 4,
		sotBattleHero = 5,
		sotTrigger = 6,
		sotTotal = 7,
	}

	public enum KDoodadType
	{
		dddInvalid = 0,
		dddCollect = 1,
		dddDrop = 2,
		dddBuffDrop = 3,
	}

	public enum KEffectObjectType
	{
		eotInvalid = 0,
		eotBonfire = 1,
		eotTeleport = 2,
	}

	public enum KTriggerObjectType
	{
		totInvalid = 0,
		totMission = 1,
	}

	public enum KPlotTimeType
	{
		pttStageTime = 0,
		pttWholeTime = 1,
	}

	public enum KNpcFuncType
	{
		KNpcFunc_Teleport = 1,
		KNpcFunc_CommonShop = 2,
		KNpcFunc_Task = 3,
		KNpcFunc_BornPos = 4,
		KNpcFunc_RelivePos = 5,
		KNpcFunc_Collect = 6,
		KNpcFunc_OpenPanel = 7,
		KNpcFunc_DailyTask = 8,
	}

	public enum KFreezeType
	{
		eftFreezeLogin = 0,
		eftBanTalk = 1,
		eftBanTalkSoli = 2,
		eftToggleTalkSoli = 3,
		eftFreezeTypeCount = 4,
		eftToggleTime = 0x0FFFFFFF,
	}

	public enum KMoveState
	{
		mosInvalid = 0,
		mosStand = 1,
		mosMove = 2,
		mosDeath = 3,
		mosForceMove = 4,
		mosEnter = 5,
		mosLeave = 6,
		mosTotal = 7,
	}

	public enum ComposableState
	{
		IsMoveForward = 0,
		IsFallBack = 1,
		IsTransLeft = 2,
		IsTransRight = 3,
		IsRun = 4,
		IsJump = 5,
		IsRising = 6,
		IsLanding = 7,
		IsAdjustDirection = 8,
		IsTurnLeft = 9,
		IsTurnRight = 10,
		IsLeapCrossSceneOut = 11,
		IsLeapCrossSceneIn = 12,
		IsSmallLeapPreparing = 13,
		IsSmallLeapCancel = 14,
		IsSmallLeapPreheat = 15,
		IsSmallLeaping = 16,
		IsSmallLeapRemoveNotify = 17,
		IsSmallLeapComplete = 18,
		IsBroken = 19,
		IsRepair = 20,
		IsReadyLeap = 21,
		IsLeapInSceneAccelerate = 22,
		IsLeapInSceneMaxSpeed = 23,
		IsLeapInSceneDecelerate = 24,
		IsLeapInSceneFinished = 25,
		FightingStatus = 26,
		CruiseStatus = 27,
		OverLoadStatus = 28,
		PeerlessStatus = 29,
		BackToAnchor = 30,
		IsTotal = 31,
	}

	public enum AircraftAttributeType
	{
		Invalid = 0,
		KineticD = 1,
		KineticDM = 2,
		KineticDRM = 3,
		KineticDR = 4,
		ReKineticDM = 5,
		ReKineticDRM = 6,
		ReRealKineticD = 7,
		ReRealKineticDR = 8,
		ThermalD = 9,
		ThermalDM = 10,
		ThermalDRM = 11,
		ThermalDR = 12,
		ReThermalDM = 13,
		ReThermalDRM = 14,
		ReRealThermalD = 15,
		ReRealThermalDR = 16,
		NuclearD = 17,
		NuclearDM = 18,
		NuclearDRM = 19,
		NuclearDR = 20,
		ReNuclearDM = 21,
		ReNuclearDRM = 22,
		ReRealNuclearD = 23,
		ReRealNuclearDR = 24,
		ElectricArcD = 25,
		ElectricArcDM = 26,
		ElectricArcDRM = 27,
		ElectricArcR = 28,
		ReElectricArcDM = 29,
		ReElectricArcDRM = 30,
		ReRealElectricArcD = 31,
		ReRealElectricArcDR = 32,
		FreezeD = 33,
		FreezeDM = 34,
		FreezeDRM = 35,
		FreezeR = 36,
		ReFreezeDM = 37,
		ReFreezeDRM = 38,
		ReRealFreezeD = 39,
		ReRealFreezeDR = 40,
		OpticalRadiationD = 41,
		OpticalRadiationDM = 42,
		OpticalRadiationDRM = 43,
		OpticalRadiationR = 44,
		ReOpticalRadiationDM = 45,
		ReOpticalRadiationDRM = 46,
		ReRealOpticalRadiationD = 47,
		ReRealOpticalRadiationDR = 48,
		DarkCorrosionD = 49,
		DarkCorrosionDM = 50,
		DarkCorrosionDRM = 51,
		DarkCorrosionR = 52,
		ReDarkCorrosionDM = 53,
		ReDarkCorrosionDRM = 54,
		ReRealDarkCorrosionD = 55,
		ReRealDarkCorrosionDR = 56,
		NatureDM = 57,
		NatureDRM = 58,
		NatureR = 59,
		ReNatureDM = 60,
		ReNatureDRM = 61,
		ReRealNatureD = 62,
		ReRealNatureDR = 63,
		ArtilleryDM = 64,
		ArtilleryDRM = 65,
		ArtilleryR = 66,
		ReArtilleryDM = 67,
		ReArtilleryDRM = 68,
		MissileDM = 69,
		MissileDRM = 70,
		MissileR = 71,
		ReMissileDM = 72,
		ReMissileDRM = 73,
		LaserDM = 74,
		LaserDRM = 75,
		LaserR = 76,
		ReLaserDM = 77,
		ReLaserDRM = 78,
		GrenadeDM = 79,
		GrenadeDRM = 80,
		GrenadeR = 81,
		ReGrenadeDM = 82,
		ReGrenadeDRM = 83,
		UAVDM = 84,
		UAVDRM = 85,
		UAVR = 86,
		ReUAVDM = 87,
		ReUAVDRM = 88,
		Critical = 89,
		CriticalR = 90,
		CriticalM = 91,
		CriticalRM = 92,
		ReCriticalM = 93,
		ReCriticalRM = 94,
		CriticalRate = 95,
		CriticalRateR = 96,
		CriticalD = 97,
		CriticalDR = 98,
		CriticalDM = 99,
		CriticalDRM = 100,
		ReCriticalDM = 101,
		ReCriticalDRM = 102,
		CriticalDPercent = 103,
		CriticalDPercentR = 104,
		ReCriticalDPercent = 105,
		ReCriticalDPercentR = 106,
		CriticalDAdd = 107,
		Penetration = 108,
		PenetrationR = 109,
		PenetrationM = 110,
		PenetrationRM = 111,
		RePenetrationM = 112,
		RePenetrationRM = 113,
		PenetrationRate = 114,
		PenetrationRateR = 115,
		PenetrabilityD = 116,
		PenetrabilityDR = 117,
		PenetrabilityDM = 118,
		PenetrabilityDRM = 119,
		RePenetrabilityDM = 120,
		RePenetrabilityDRM = 121,
		PenetrabilityDPercent = 122,
		PenetrabilityDPercentR = 123,
		RePenetrabilityDPercent = 124,
		RePenetrabilityDPercentR = 125,
		PenetrationDMR = 126,
		ArtilleryPenetrability = 127,
		ArtilleryPenetrabilityR = 128,
		ArtilleryPenetrabilityM = 129,
		ArtilleryPenetrabilityRM = 130,
		ReArtilleryPenetrabilityM = 131,
		ReArtilleryPenetrabilityRM = 132,
		ArtilleryPenetrabilityRate = 133,
		ReArtilleryPenetrabilityRate = 134,
		MissilePenetrability = 135,
		MissilePenetrabilityR = 136,
		MissilePenetrabilityM = 137,
		MissilePenetrabilityRM = 138,
		ReMissilePenetrabilityM = 139,
		ReMissilePenetrabilityRM = 140,
		MissilePenetrabilityRate = 141,
		MissilePenetrabilityRateR = 142,
		LaserPenetrability = 143,
		LaserPenetrabilityR = 144,
		LaserPenetrabilityM = 145,
		LaserPenetrabilityRM = 146,
		ReLaserPenetrabilityM = 147,
		ReLaserPenetrabilityRM = 148,
		LaserPenetrabilityRate = 149,
		LaserPenetrabilityRateR = 150,
		GrenadePenetrability = 151,
		GrenadePenetrabilityR = 152,
		GrenadePenetrabilityM = 153,
		GrenadePenetrabilityRM = 154,
		ReGrenadePenetrabilityM = 155,
		ReGrenadePenetrabilityRM = 156,
		GrenadePenetrabilityRate = 157,
		GrenadePenetrabilityRateR = 158,
		UAVPenetrability = 159,
		UAVPenetrabilityR = 160,
		UAVPenetrabilityM = 161,
		UAVPenetrabilityRM = 162,
		ReUAVPenetrabilityM = 163,
		ReUAVPenetrabilityRM = 164,
		UAVPenetrabilityRate = 165,
		UAVPenetrabilityRateR = 166,
		ArtilleryPenetrabilityD = 167,
		ArtilleryPenetrabilityDR = 168,
		ArtilleryPenetrabilityDM = 169,
		ArtilleryPenetrabilityDRM = 170,
		ReArtilleryPenetrabilityDM = 171,
		ReArtilleryPenetrabilityDRM = 172,
		ArtilleryPenetrabilityDPercent = 173,
		ArtilleryPenetrabilityDPercentR = 174,
		ReArtilleryPenetrabilityDPercent = 175,
		REArtilleryPenetrabilityDPercentR = 176,
		ArtilleryPenetrabilityDMR = 177,
		MissilePenetrabilityD = 178,
		MissilePenetrabilityDR = 179,
		MissilePenetrabilityDM = 180,
		MissilePenetrabilityDRM = 181,
		ReMissilePenetrabilityDM = 182,
		ReMissilePenetrabilityDRM = 183,
		MissilePenetrabilityDPercent = 184,
		MissilePenetrabilityDPercentR = 185,
		ReMissilePenetrabilityDPercent = 186,
		REMissilePenetrabilityDPercentR = 187,
		MissilePenetrabilityDMR = 188,
		LaserPenetrabilityD = 189,
		LaserPenetrabilityDR = 190,
		LaserPenetrabilityDM = 191,
		LaserPenetrabilityDRM = 192,
		ReLaserPenetrabilityDM = 193,
		ReLaserPenetrabilityDRM = 194,
		LaserPenetrabilityDPercent = 195,
		LaserPenetrabilityDPercentR = 196,
		ReLaserPenetrabilityDPercent = 197,
		RELaserPenetrabilityDPercentR = 198,
		LaserPenetrabilityDMR = 199,
		GrenadePenetrabilityD = 200,
		GrenadePenetrabilityDR = 201,
		GrenadePenetrabilityDM = 202,
		GrenadePenetrabilityDRM = 203,
		ReGrenadePenetrabilityDM = 204,
		ReGrenadePenetrabilityDRM = 205,
		GrenadePenetrabilityDPercent = 206,
		GrenadePenetrabilityDPercentR = 207,
		ReGrenadePenetrabilityDPercent = 208,
		ReGrenadePenetrabilityDPercentR = 209,
		GrenadePenetrabilityDMR = 210,
		UAVPenetrabilityD = 211,
		UAVPenetrabilityDR = 212,
		UAVPenetrabilityDM = 213,
		UAVPenetrabilityDRM = 214,
		ReUAVPenetrabilityDM = 215,
		ReUAVPenetrabilityDRM = 216,
		UAVPenetrabilityDPercent = 217,
		UAVPenetrabilityDPercentR = 218,
		ReUAVPenetrabilityDPercent = 219,
		REUAVPenetrabilityDPercentR = 220,
		UAVPenetrabilityDMR = 221,
		ArtilleryCritical = 222,
		ArtilleryCriticalR = 223,
		ArtilleryCriticalM = 224,
		ArtilleryCriticalRM = 225,
		ReArtilleryCriticalM = 226,
		ReArtilleryCriticalRM = 227,
		ArtilleryCriticalRate = 228,
		ArtilleryCriticalRateR = 229,
		MissileCritical = 230,
		MissileCriticalR = 231,
		MissileCriticalM = 232,
		MissileCriticalRM = 233,
		ReMissileCriticalM = 234,
		ReMissileCriticalRM = 235,
		MissileCriticalRate = 236,
		MissileCriticalRateR = 237,
		LaserCritical = 238,
		LaserCriticalR = 239,
		LaserCriticalM = 240,
		LaserCriticalRM = 241,
		ReLaserCriticalM = 242,
		ReLaserCriticalRM = 243,
		LaserCriticalRate = 244,
		LaserCriticalRateR = 245,
		GrenadeCritical = 246,
		GrenadeCriticalR = 247,
		GrenadeCriticalM = 248,
		GrenadeCriticalRM = 249,
		ReGrenadeCriticalM = 250,
		ReGrenadeCriticalRM = 251,
		GrenadeCriticalRate = 252,
		GrenadeCriticalRateR = 253,
		UAVCritical = 254,
		UAVCriticalR = 255,
		UAVCriticalM = 256,
		UAVCriticalRM = 257,
		ReUAVCriticalM = 258,
		ReUAVCriticalRM = 259,
		UAVCriticalRate = 260,
		UAVCriticalRateR = 261,
		ArtilleryCriticalD = 262,
		ArtilleryCriticalDR = 263,
		ArtilleryCriticalDM = 264,
		ArtilleryCriticalDRM = 265,
		ReArtilleryCriticalDM = 266,
		ReArtilleryCriticalDRM = 267,
		ArtilleryCriticalDPercent = 268,
		ArtilleryCriticalDPercentR = 269,
		ReArtilleryCriticalDPercent = 270,
		ReArtilleryCriticalDPercentR = 271,
		ArtilleryCriticalDMR = 272,
		MissileCriticalD = 273,
		MissileCriticalDR = 274,
		MissileCriticalDM = 275,
		MissileCriticalDRM = 276,
		ReMissileCriticalDM = 277,
		ReMissileCriticalDRM = 278,
		MissileCriticalDPercent = 279,
		MissileCriticalDPercentR = 280,
		ReMissileCriticalDPercent = 281,
		ReMissileCriticalDPercentR = 282,
		MissileCriticalDMR = 283,
		LaserCriticalD = 284,
		LaserCriticalDR = 285,
		LaserCriticalDM = 286,
		LaserCriticalDRM = 287,
		ReLaserCriticalDM = 288,
		ReLaserCriticalDRM = 289,
		LaserCriticalDPercent = 290,
		LaserCriticalDPercentR = 291,
		ReLaserCriticalDPercent = 292,
		ReLaserCriticalDPercentR = 293,
		LaserCriticalDMR = 294,
		GrenadeCriticalD = 295,
		GrenadeCriticalDR = 296,
		GrenadeCriticalDM = 297,
		GrenadeCriticalDRM = 298,
		ReGrenadeCriticalDM = 299,
		ReGrenadeCriticalDRM = 300,
		GrenadeCriticalDPercent = 301,
		GrenadeCriticalDPercentR = 302,
		ReGrenadeCriticalDPercent = 303,
		ReGrenadeCriticalDPercentR = 304,
		GrenadeCriticalDMR = 305,
		UAVCriticalD = 306,
		UAVCriticalDR = 307,
		UAVCriticalDM = 308,
		UAVCriticalDRM = 309,
		ReUAVCriticalDM = 310,
		ReUAVCriticalDRM = 311,
		UAVCriticalDPercent = 312,
		UAVCriticalDPercentR = 313,
		ReUAVCriticalDPercent = 314,
		ReUAVCriticalDPercentR = 315,
		UAVCriticalDMR = 316,
		BuffChance = 317,
		BuffChanceR = 318,
		BuffChanceM = 319,
		BuffChanceRM = 320,
		ReBuffChanceM = 321,
		ReBuffChanceRM = 322,
		ShieldD = 323,
		ShieldDR = 324,
		ShieldDM = 325,
		ShieldDRM = 326,
		ReShieldDM = 327,
		ReShieldDRM = 328,
		ArtilleryShieldD = 329,
		ArtilleryShieldDR = 330,
		ArtilleryShieldDM = 331,
		ArtilleryShieldDRM = 332,
		ReArtilleryShieldDM = 333,
		ReArtilleryShieldDRM = 334,
		MissileShieldD = 335,
		MissileShieldDR = 336,
		MissileShieldDM = 337,
		MissileShieldDRM = 338,
		ReMissileShieldDM = 339,
		ReMissileShieldDRM = 340,
		LaserShieldD = 341,
		LaserShieldDR = 342,
		LaserShieldDM = 343,
		LaserShieldDRM = 344,
		ReLaserShieldDM = 345,
		ReLaserShieldDRM = 346,
		GrenadeShieldD = 347,
		GrenadeShieldDR = 348,
		GrenadeShieldDM = 349,
		GrenadeShieldDRM = 350,
		ReGrenadeShieldDM = 351,
		ReGrenadeShieldDRM = 352,
		UAVShieldD = 353,
		UAVShieldDR = 354,
		UAVShieldDM = 355,
		UAVShieldDRM = 356,
		ReUAVShieldDM = 357,
		ReUAVShieldDRM = 358,
		ArmorD = 359,
		ArmorDR = 360,
		ArmorDM = 361,
		ArmorDRM = 362,
		ReArmorDM = 363,
		ReArmorDRM = 364,
		ManaShield = 365,
		ManaShieldTopLimit = 366,
		ManaShieldEfficiency = 367,
		ManaShieldOffsetRate = 368,
		ManaShieldOffseKinetic = 369,
		ManaShieldOffseThermal = 370,
		ManaShieldOffseNuclear = 371,
		ManaShieldOffseElectricArc = 372,
		ManaShieldOffseFreeze = 373,
		ManaShieldOffseOpticalRadiation = 374,
		ManaShieldOffseDarkCorrosion = 375,
		ManaShieldOffsePenetrability = 376,
		DefenseShield = 377,
		DefenseShieldTopLimit = 378,
		DefenseShieldOffsetRate = 379,
		DefenseShieldOffseKinetic = 380,
		DefenseShieldOffseThermal = 381,
		DefenseShieldOffseNuclear = 382,
		DefenseShieldOffseElectricArc = 383,
		DefenseShieldOffseFreeze = 384,
		DefenseShieldOffseOpticalRadiation = 385,
		DefenseShieldOffseDarkCorrosion = 386,
		DefenseShieldOffsePenetrability = 387,
		Hit = 388,
		Dodge = 389,
		HitM = 390,
		HitRM = 391,
		DodgeM = 392,
		DodgeRM = 393,
		ArtilleryHit = 394,
		MissileHit = 395,
		LaserHit = 396,
		GrenadeHit = 397,
		UAVHit = 398,
		ArtilleryDodge = 399,
		MissileDodge = 400,
		LaserDodge = 401,
		GrenadeDodge = 402,
		UAVDodge = 403,
		ArtilleryHitM = 404,
		ArtilleryHitRM = 405,
		MissileHitM = 406,
		MissileHitRM = 407,
		LaserHitM = 408,
		LaserHitRM = 409,
		GrenadeHitM = 410,
		GrenadeHitRM = 411,
		UAVHitM = 412,
		UAVHitRM = 413,
		ArtilleryDodgeM = 414,
		ArtilleryDodgeRM = 415,
		MissileDodgeM = 416,
		MissileDodgeRM = 417,
		LaserDodgeM = 418,
		LaserDodgeRM = 419,
		GrenadeDodgeM = 420,
		GrenadeDodgeRM = 421,
		UAVDodgeM = 422,
		UAVDodgeRM = 423,
		HitRate = 424,
		DodgeHitRate = 425,
		SpeedToHitCoefficient = 426,
		ArtilleryHitRate = 427,
		MissileHitRate = 428,
		LaserHitRate = 429,
		GrenadeHitRate = 430,
		UAVHitRate = 431,
		ArtilleryDodgeRate = 432,
		MissileDodgeRate = 433,
		LaserDodgeRate = 434,
		GrenadeDodgeRate = 435,
		UAVDodgeRate = 436,
		HP = 437,
		HPTopLimit = 438,
		HPRecoveryPerSecIB = 439,
		HPRecoveryPerSecIBM = 440,
		HPRecoveryPerSecIBRM = 441,
		HPRecoveryDelayIB = 442,
		HPRecoveryDelayIBM = 443,
		HPRecoveryDelayIBRM = 444,
		HPRecoveryPerSecOB = 445,
		HPRecoveryPerSecOBM = 446,
		HPRecoveryPerSecOBRM = 447,
		HPRecoveryDelayOB = 448,
		HPRecoveryDelayOBM = 449,
		HPRecoveryDelayOBRM = 450,
		Shield = 451,
		ShieldTopLimit = 452,
		ShieldRechargePerSecIB = 453,
		ShieldRechargePerSecIBM = 454,
		ShieldRechargePerSecIBRM = 455,
		ShieldRechargeDelayIB = 456,
		ShieldRechargeDelayIBM = 457,
		ShieldRechargeDelayIBRM = 458,
		ShieldRechargePerSecOB = 459,
		ShieldRechargePerSecOBM = 460,
		ShieldRechargePerSecOBRM = 461,
		ShieldRechargeDelayOB = 462,
		ShieldRechargeDelayOBM = 463,
		ShieldRechargeDelayOBRM = 464,
		EnergyPower = 465,
		EnergyPowerTopLimit = 466,
		EnergyRechargePerSecIB = 467,
		EnergyRechargePerSecIBM = 468,
		EnergyRechargePerSecIBRM = 469,
		EnergyRechargeDelayIB = 470,
		EnergyRechargeDelayIBM = 471,
		EnergyRechargeDelayIBRM = 472,
		EnergyRechargePerSecOB = 473,
		EnergyRechargePerSecOBM = 474,
		EnergyRechargePerSecOBRM = 475,
		EnergyRechargeDelayOB = 476,
		EnergyRechargeDelayOBM = 477,
		EnergyRechargeDelayOBRM = 478,
		SuperMagnetic = 479,
		SuperMagneticTopLimit = 480,
		SMRechargePerSecIB = 481,
		SMRechargePerSecIBM = 482,
		SMRechargePerSecIBRM = 483,
		SMRechargeDelayIB = 484,
		SMRechargeDelayIBM = 485,
		SMRechargeDelayIBRM = 486,
		SMDeclinePerSecOB = 487,
		SMDeclinePerSecOBM = 488,
		SMDeclinePerSecOBRM = 489,
		SMDeclineDelayOB = 490,
		SMDeclineDelayOBM = 491,
		SMDeclineDelayOBRM = 492,
		LockingRadius = 493,
		RadiiOfSight = 494,
		RangeOfFire = 495,
		ArtilleryRange = 496,
		MissileRange = 497,
		LaserRange = 498,
		GrenadeRange = 499,
		UAVRange = 500,
		RangeOfFireM = 501,
		ArtilleryRangeM = 502,
		MissileRangeM = 503,
		LaserRangeM = 504,
		GrenadeRangeM = 505,
		UAVRangeM = 506,
		RangeOfFireRM = 507,
		ArtilleryRangeRM = 508,
		MissileRangeRM = 509,
		LaserRangeRM = 510,
		GrenadeRangeRM = 511,
		UAVRangeRM = 512,
		GatlinKineticD = 513,
		GatlinThermalD = 514,
		GatlinNuclearD = 515,
		GatlinElectricArcD = 516,
		GatlinFreezeD = 517,
		GatlinOpticalRadiationD = 518,
		GatlinDarkCorrosionD = 519,
		GatlinKineticDM = 520,
		GatlinKineticDRM = 521,
		GatlinThermalDM = 522,
		GatlinThermalDRM = 523,
		GatlinNuclearDM = 524,
		GatlinNuclearDRM = 525,
		GatlinElectricArcDM = 526,
		GatlinElectricArcDRM = 527,
		GatlinFreezeDM = 528,
		GatlinFreezeDRM = 529,
		GatlinOpticalRadiationDM = 530,
		GatlinOpticalRadiationDRM = 531,
		GatlinDarkCorrosionDM = 532,
		GatlinDarkCorrosionDRM = 533,
		GatlinDM = 534,
		GatlinDRM = 535,
		GatlinDR = 536,
		ReGatlinDM = 537,
		ReGatlinDRM = 538,
		GatlinPenetrability = 539,
		GatlinPenetrabilityR = 540,
		GatlinPenetrabilityM = 541,
		GatlinPenetrabilityRM = 542,
		ReGatlinPenetrabilityM = 543,
		ReGatlinPenetrabilityRM = 544,
		GatlinPenetrabilityRate = 545,
		GatlinPenetrabilityRateR = 546,
		GatlinPenetrabilityD = 547,
		GatlinPenetrabilityDR = 548,
		GatlinPenetrabilityDM = 549,
		GatlinPenetrabilityDRM = 550,
		ReGatlinPenetrabilityDM = 551,
		ReGatlinPenetrabilityDRM = 552,
		GatlinPenetrabilityDPercent = 553,
		GatlinPenetrabilityDPercentR = 554,
		ReGatlinPenetrabilityDPercent = 555,
		ReGatlinPenetrabilityDPercentR = 556,
		GatlinPenetrabilityDMR = 557,
		GatlinCritical = 558,
		GatlinCriticalR = 559,
		GatlinCriticalM = 560,
		GatlinCriticalRM = 561,
		GatlinReCriticalM = 562,
		GatlinReCriticalRM = 563,
		GatlinCriticalRate = 564,
		GatlinCriticalRateR = 565,
		GatlinCriticalD = 566,
		GatlinCriticalDR = 567,
		GatlinCriticalDM = 568,
		GatlinCriticalDRM = 569,
		ReGatlinCriticalDM = 570,
		ReGatlinCriticalDRM = 571,
		GatlinCriticalDPercent = 572,
		GatlinCriticalDPercentR = 573,
		ReGatlinCriticalDPercent = 574,
		ReGatlinCriticalDPercentR = 575,
		GatlinCriticalDMR = 576,
		GatlinShieldD = 577,
		GatlinShieldDR = 578,
		GatlinShieldDM = 579,
		GatlinShieldDRM = 580,
		ReGatlinShieldDM = 581,
		ReGatlinShieldDRM = 582,
		GatlinHit = 583,
		GatlinDodgeHit = 584,
		GatlinHitM = 585,
		GatlinHitRM = 586,
		GatlinDodgeHitM = 587,
		GatlinDodgeHitRM = 588,
		GatlinHitRate = 589,
		GatlinDodgeHitRate = 590,
		GatlinRange = 591,
		GatlinRangeM = 592,
		GatlinRangeRM = 593,
		CanonKineticD = 594,
		CanonThermalD = 595,
		CanonNuclearD = 596,
		CanonElectricArcD = 597,
		CanonFreezeD = 598,
		CanonOpticalRadiationD = 599,
		CanonDarkCorrosionD = 600,
		CanonKineticDM = 601,
		CanonKineticDRM = 602,
		CanonThermalDM = 603,
		CanonThermalDRM = 604,
		CanonNuclearDM = 605,
		CanonNuclearDRM = 606,
		CanonElectricArcDM = 607,
		CanonElectricArcDRM = 608,
		CanonFreezeDM = 609,
		CanonFreezeDRM = 610,
		CanonOpticalRadiationDM = 611,
		CanonOpticalRadiationDRM = 612,
		CanonDarkCorrosionDM = 613,
		CanonDarkCorrosionDRM = 614,
		CanonDM = 615,
		CanonDRM = 616,
		CanonDR = 617,
		ReCanonDM = 618,
		ReCanonDRM = 619,
		CanonPenetrability = 620,
		CanonPenetrabilityR = 621,
		CanonPenetrabilityM = 622,
		CanonPenetrabilityRM = 623,
		ReCanonPenetrabilityM = 624,
		ReCanonPenetrabilityRM = 625,
		CanonPenetrabilityRate = 626,
		CanonPenetrabilityRateR = 627,
		CanonPenetrabilityD = 628,
		CanonPenetrabilityDR = 629,
		CanonPenetrabilityDM = 630,
		CanonPenetrabilityDRM = 631,
		ReCanonPenetrabilityDM = 632,
		ReCanonPenetrabilityDRM = 633,
		CanonPenetrabilityDPercent = 634,
		CanonPenetrabilityDPercentR = 635,
		ReCanonPenetrabilityDPercent = 636,
		ReCanonPenetrabilityDPercentR = 637,
		CanonPenetrabilityDMR = 638,
		CanonCritical = 639,
		CanonCriticalR = 640,
		CanonCriticalM = 641,
		CanonCriticalRM = 642,
		CanonReCriticalM = 643,
		CanonReCriticalRM = 644,
		CanonCriticalRate = 645,
		CanonCriticalRateR = 646,
		CanonCriticalD = 647,
		CanonCriticalDR = 648,
		CanonCriticalDM = 649,
		CanonCriticalDRM = 650,
		ReCanonCriticalDM = 651,
		ReCanonCriticalDRM = 652,
		CanonCriticalDPercent = 653,
		CanonCriticalDPercentR = 654,
		ReCanonCriticalDPercent = 655,
		ReCanonCriticalDPercentR = 656,
		CanonCriticalDMR = 657,
		CanonShieldD = 658,
		CanonShieldDR = 659,
		CanonShieldDM = 660,
		CanonShieldDRM = 661,
		ReCanonShieldDM = 662,
		ReCanonShieldDRM = 663,
		CanonHit = 664,
		CanonDodgeHit = 665,
		CanonHitM = 666,
		CanonHitRM = 667,
		CanonDodgeHitM = 668,
		CanonDodgeHitRM = 669,
		CanonHitRate = 670,
		CanonDodgeHitRate = 671,
		CanonRange = 672,
		CanonRangeM = 673,
		CanonRangeRM = 674,
		TacticsMissileKineticD = 675,
		TacticsMissileThermalD = 676,
		TacticsMissileNuclearD = 677,
		TacticsMissileElectricArcD = 678,
		TacticsMissileFreezeD = 679,
		TacticsMissileOpticalRadiationD = 680,
		TacticsMissileDarkCorrosionD = 681,
		TacticsMissileKineticDM = 682,
		TacticsMissileKineticDRM = 683,
		TacticsMissileThermalDM = 684,
		TacticsMissileThermalDRM = 685,
		TacticsMissileNuclearDM = 686,
		TacticsMissileNuclearDRM = 687,
		TacticsMissileElectricArcDM = 688,
		TacticsMissileElectricArcDRM = 689,
		TacticsMissileFreezeDM = 690,
		TacticsMissileFreezeDRM = 691,
		TacticsMissileOpticalRadiationDM = 692,
		TacticsMissileOpticalRadiationDRM = 693,
		TacticsMissileDarkCorrosionDM = 694,
		TacticsMissileDarkCorrosionDRM = 695,
		TacticsMissileDM = 696,
		TacticsMissileDRM = 697,
		TacticsMissileDR = 698,
		ReTacticsMissileDM = 699,
		ReTacticsMissileDRM = 700,
		TacticsMissilePenetrability = 701,
		TacticsMissilePenetrabilityR = 702,
		TacticsMissilePenetrabilityM = 703,
		TacticsMissilePenetrabilityRM = 704,
		ReTacticsMissilePenetrabilityM = 705,
		ReTacticsMissilePenetrabilityRM = 706,
		TacticsMissilePenetrabilityRate = 707,
		TacticsMissilePenetrabilityRateR = 708,
		TacticsMissilePenetrabilityD = 709,
		TacticsMissilePenetrabilityDR = 710,
		TacticsMissilePenetrabilityDM = 711,
		TacticsMissilePenetrabilityDRM = 712,
		ReTacticsMissilePenetrabilityDM = 713,
		ReTacticsMissilePenetrabilityDRM = 714,
		TacticsMissilePenetrabilityDP = 715,
		TacticsMissilePenetrabilityDPR = 716,
		ReTacticsMissilePenetrabilityDP = 717,
		ReTacticsMissilePenetrabilityDPR = 718,
		TacticsMissilePenetrabilityDMR = 719,
		TacticsMissileCritical = 720,
		TacticsMissileCriticalR = 721,
		TacticsMissileCriticalM = 722,
		TacticsMissileCriticalRM = 723,
		TacticsMissileReCriticalM = 724,
		TacticsMissileReCriticalRM = 725,
		TacticsMissileCriticalRate = 726,
		TacticsMissileCriticalRateR = 727,
		TacticsMissileCriticalD = 728,
		TacticsMissileCriticalDR = 729,
		TacticsMissileCriticalDM = 730,
		TacticsMissileCriticalDRM = 731,
		ReTacticsMissileCriticalDM = 732,
		ReTacticsMissileCriticalDRM = 733,
		TacticsMissileCriticalDPercent = 734,
		TacticsMissileCriticalDPercentR = 735,
		ReTacticsMissileCriticalDPercent = 736,
		ReTacticsMissileCriticalDPercentR = 737,
		TacticsMissileCriticalDMR = 738,
		TacticsMissileShieldD = 739,
		TacticsMissileShieldDR = 740,
		TacticsMissileShieldDM = 741,
		TacticsMissileShieldDRM = 742,
		ReTacticsMissileShieldDM = 743,
		ReTacticsMissileShieldDRM = 744,
		TacticsMissileHit = 745,
		TacticsMissileDodgeHit = 746,
		TacticsMissileHitM = 747,
		TacticsMissileHitRM = 748,
		TacticsMissileDodgeHitM = 749,
		TacticsMissileDodgeHitRM = 750,
		TacticsMissileHitRate = 751,
		TacticsMissileDodgeHitRate = 752,
		TacticsMissileRange = 753,
		TacticsMissileRangeM = 754,
		TacticsMissileRangeRM = 755,
		RocketKineticD = 756,
		RocketThermalD = 757,
		RocketNuclearD = 758,
		RocketElectricArcD = 759,
		RocketFreezeD = 760,
		RocketOpticalRadiationD = 761,
		RocketDarkCorrosionD = 762,
		RocketKineticDM = 763,
		RocketKineticDRM = 764,
		RocketThermalDM = 765,
		RocketThermalDRM = 766,
		RocketNuclearDM = 767,
		RocketNuclearDRM = 768,
		RocketElectricArcDM = 769,
		RocketElectricArcDRM = 770,
		RocketFreezeDM = 771,
		RocketFreezeDRM = 772,
		RocketOpticalRadiationDM = 773,
		RocketOpticalRadiationDRM = 774,
		RocketDarkCorrosionDM = 775,
		RocketDarkCorrosionDRM = 776,
		RocketDM = 777,
		RocketDRM = 778,
		RocketDR = 779,
		ReRocketDM = 780,
		ReRocketDRM = 781,
		RocketPenetrability = 782,
		RocketPenetrabilityR = 783,
		RocketPenetrabilityM = 784,
		RocketPenetrabilityRM = 785,
		ReRocketPenetrabilityM = 786,
		ReRocketPenetrabilityRM = 787,
		RocketPenetrabilityRate = 788,
		RocketPenetrabilityRateR = 789,
		RocketPenetrabilityD = 790,
		RocketPenetrabilityDR = 791,
		RocketPenetrabilityDM = 792,
		RocketPenetrabilityDRM = 793,
		ReRocketPenetrabilityDM = 794,
		ReRocketPenetrabilityDRM = 795,
		RocketPenetrabilityDPercent = 796,
		RocketPenetrabilityDPercentR = 797,
		ReRocketPenetrabilityDPercent = 798,
		ReRocketPenetrabilityDPercentR = 799,
		RocketPenetrabilityDMR = 800,
		RocketCritical = 801,
		RocketCriticalR = 802,
		RocketCriticalM = 803,
		RocketCriticalRM = 804,
		RocketReCriticalM = 805,
		RocketReCriticalRM = 806,
		RocketCriticalRate = 807,
		RocketCriticalRateR = 808,
		RocketCriticalD = 809,
		RocketCriticalDR = 810,
		RocketCriticalDM = 811,
		RocketCriticalDRM = 812,
		ReRocketCriticalDM = 813,
		ReRocketCriticalDRM = 814,
		RocketCriticalDPercent = 815,
		RocketCriticalDPercentR = 816,
		ReRocketCriticalDPercent = 817,
		ReRocketCriticalDPercentR = 818,
		RocketCriticalDMR = 819,
		RocketShieldD = 820,
		RocketShieldDR = 821,
		RocketShieldDM = 822,
		RocketShieldDRM = 823,
		ReRocketShieldDM = 824,
		ReRocketShieldDRM = 825,
		RocketHit = 826,
		RocketDodgeHit = 827,
		RocketHitM = 828,
		RocketHitRM = 829,
		RocketDodgeHitM = 830,
		RocketDodgeHitRM = 831,
		RocketHitRate = 832,
		RocketDodgeHitRate = 833,
		RocketRange = 834,
		RocketRangeM = 835,
		RocketRangeRM = 836,
		TorpedoKineticD = 837,
		TorpedoThermalD = 838,
		TorpedoNuclearD = 839,
		TorpedoElectricArcD = 840,
		TorpedoFreezeD = 841,
		TorpedoOpticalRadiationD = 842,
		TorpedoDarkCorrosionD = 843,
		TorpedoKineticDM = 844,
		TorpedoKineticDRM = 845,
		TorpedoThermalDM = 846,
		TorpedoThermalDRM = 847,
		TorpedoNuclearDM = 848,
		TorpedoNuclearDRM = 849,
		TorpedoElectricArcDM = 850,
		TorpedoElectricArcDRM = 851,
		TorpedoFreezeDM = 852,
		TorpedoFreezeDRM = 853,
		TorpedoOpticalRadiationDM = 854,
		TorpedoOpticalRadiationDRM = 855,
		TorpedoDarkCorrosionDM = 856,
		TorpedoDarkCorrosionDRM = 857,
		TorpedoDM = 858,
		TorpedoDRM = 859,
		TorpedoDR = 860,
		ReTorpedoDM = 861,
		ReTorpedoDRM = 862,
		TorpedoPenetrability = 863,
		TorpedoPenetrabilityR = 864,
		TorpedoPenetrabilityM = 865,
		TorpedoPenetrabilityRM = 866,
		ReTorpedoPenetrabilityM = 867,
		ReTorpedoPenetrabilityRM = 868,
		TorpedoPenetrabilityRate = 869,
		TorpedoPenetrabilityRateR = 870,
		TorpedoPenetrabilityD = 871,
		TorpedoPenetrabilityDR = 872,
		TorpedoPenetrabilityDM = 873,
		TorpedoPenetrabilityDRM = 874,
		ReTorpedoPenetrabilityDM = 875,
		ReTorpedoPenetrabilityDRM = 876,
		TorpedoPenetrabilityDPercent = 877,
		TorpedoPenetrabilityDPercentR = 878,
		ReTorpedoPenetrabilityDPercent = 879,
		ReTorpedoPenetrabilityDPercentR = 880,
		TorpedoPenetrabilityDMR = 881,
		TorpedoCritical = 882,
		TorpedoCriticalR = 883,
		TorpedoCriticalM = 884,
		TorpedoCriticalRM = 885,
		TorpedoReCriticalM = 886,
		TorpedoReCriticalRM = 887,
		TorpedoCriticalRate = 888,
		TorpedoCriticalRateR = 889,
		TorpedoCriticalD = 890,
		TorpedoCriticalDR = 891,
		TorpedoCriticalDM = 892,
		TorpedoCriticalDRM = 893,
		ReTorpedoCriticalDM = 894,
		ReTorpedoCriticalDRM = 895,
		TorpedoCriticalDPercent = 896,
		TorpedoCriticalDPercentR = 897,
		ReTorpedoCriticalDPercent = 898,
		ReTorpedoCriticalDPercentR = 899,
		TorpedoCriticalDMR = 900,
		TorpedoShieldD = 901,
		TorpedoShieldDR = 902,
		TorpedoShieldDM = 903,
		TorpedoShieldDRM = 904,
		ReTorpedoShieldDM = 905,
		ReTorpedoShieldDRM = 906,
		TorpedoHit = 907,
		TorpedoDodgeHit = 908,
		TorpedoHitM = 909,
		TorpedoHitRM = 910,
		TorpedoDodgeHitM = 911,
		TorpedoDodgeHitRM = 912,
		TorpedoHitRate = 913,
		TorpedoDodgeHitRate = 914,
		TorpedoRange = 915,
		TorpedoRangeM = 916,
		TorpedoRangeRM = 917,
		TacticsLaserKineticD = 918,
		TacticsLaserThermalD = 919,
		TacticsLaserNuclearD = 920,
		TacticsLaserElectricArcD = 921,
		TacticsLaserFreezeD = 922,
		TacticsLaserOpticalRadiationD = 923,
		TacticsLaserDarkCorrosionD = 924,
		TacticsLaserKineticDM = 925,
		TacticsLaserKineticDRM = 926,
		TacticsLaserThermalDM = 927,
		TacticsLaserThermalDRM = 928,
		TacticsLaserNuclearDM = 929,
		TacticsLaserNuclearDRM = 930,
		TacticsLaserElectricArcDM = 931,
		TacticsLaserElectricArcDRM = 932,
		TacticsLaserFreezeDM = 933,
		TacticsLaserFreezeDRM = 934,
		TacticsLaserOpticalRadiationDM = 935,
		TacticsLaserOpticalRadiationDRM = 936,
		TacticsLaserDarkCorrosionDM = 937,
		TacticsLaserDarkCorrosionDRM = 938,
		TacticsLaserDM = 939,
		TacticsLaserDRM = 940,
		TacticsLaserDR = 941,
		ReTacticsLaserDM = 942,
		ReTacticsLaserDRM = 943,
		TacticsLaserPenetrability = 944,
		TacticsLaserPenetrabilityR = 945,
		TacticsLaserPenetrabilityM = 946,
		TacticsLaserPenetrabilityRM = 947,
		ReTacticsLaserPenetrabilityM = 948,
		ReTacticsLaserPenetrabilityRM = 949,
		TacticsLaserPenetrabilityRate = 950,
		TacticsLaserPenetrabilityRateR = 951,
		TacticsLaserPenetrabilityD = 952,
		TacticsLaserPenetrabilityDR = 953,
		TacticsLaserPenetrabilityDM = 954,
		TacticsLaserPenetrabilityDRM = 955,
		ReTacticsLaserPenetrabilityDM = 956,
		ReTacticsLaserPenetrabilityDRM = 957,
		TacticsLaserPenetrabilityDPercent = 958,
		TacticsLaserPenetrabilityDPR = 959,
		ReTacticsLaserPenetrabilityDP = 960,
		ReTacticsLaserPenetrabilityDPR = 961,
		TacticsLaserPenetrabilityDMR = 962,
		TacticsLaserCritical = 963,
		TacticsLaserCriticalR = 964,
		TacticsLaserCriticalM = 965,
		TacticsLaserCriticalRM = 966,
		TacticsLaserReCriticalM = 967,
		TacticsLaserReCriticalRM = 968,
		TacticsLaserCriticalRate = 969,
		TacticsLaserCriticalRateR = 970,
		TacticsLaserCriticalD = 971,
		TacticsLaserCriticalDR = 972,
		TacticsLaserCriticalDM = 973,
		TacticsLaserCriticalDRM = 974,
		ReTacticsLaserCriticalDM = 975,
		ReTacticsLaserCriticalDRM = 976,
		TacticsLaserCriticalDPercent = 977,
		TacticsLaserCriticalDPercentR = 978,
		ReTacticsLaserCriticalDPercent = 979,
		ReTacticsLaserCriticalDPercentR = 980,
		TacticsLaserCriticalDMR = 981,
		TacticsLaserShieldD = 982,
		TacticsLaserShieldDR = 983,
		TacticsLaserShieldDM = 984,
		TacticsLaserShieldDRM = 985,
		ReTacticsLaserShieldDM = 986,
		ReTacticsLaserShieldDRM = 987,
		TacticsLaserHit = 988,
		TacticsLaserDodgeHit = 989,
		TacticsLaserHitM = 990,
		TacticsLaserHitRM = 991,
		TacticsLaserDodgeHitM = 992,
		TacticsLaserDodgeHitRM = 993,
		TacticsLaserHitRate = 994,
		TacticsLaserDodgeHitRate = 995,
		TacticsLaserRange = 996,
		TacticsLaserRangeM = 997,
		TacticsLaserRangeRM = 998,
		PulseKineticD = 999,
		PulseThermalD = 1000,
		PulseNuclearD = 1001,
		PulseElectricArcD = 1002,
		PulseFreezeD = 1003,
		PulseOpticalRadiationD = 1004,
		PulseDarkCorrosionD = 1005,
		PulseKineticDM = 1006,
		PulseKineticDRM = 1007,
		PulseThermalDM = 1008,
		PulseThermalDRM = 1009,
		PulseNuclearDM = 1010,
		PulseNuclearDRM = 1011,
		PulseElectricArcDM = 1012,
		PulseElectricArcDRM = 1013,
		PulseFreezeDM = 1014,
		PulseFreezeDRM = 1015,
		PulseOpticalRadiationDM = 1016,
		PulseOpticalRadiationDRM = 1017,
		PulseDarkCorrosionDM = 1018,
		PulseDarkCorrosionDRM = 1019,
		PulseDM = 1020,
		PulseDRM = 1021,
		PulseDR = 1022,
		RePulseDM = 1023,
		RePulseDRM = 1024,
		PulsePenetrability = 1025,
		PulsePenetrabilityR = 1026,
		PulsePenetrabilityM = 1027,
		PulsePenetrabilityRM = 1028,
		RePulsePenetrabilityM = 1029,
		RePulsePenetrabilityRM = 1030,
		PulsePenetrabilityRate = 1031,
		PulsePenetrabilityRateR = 1032,
		PulsePenetrabilityD = 1033,
		PulsePenetrabilityDR = 1034,
		PulsePenetrabilityDM = 1035,
		PulsePenetrabilityDRM = 1036,
		RePulsePenetrabilityDM = 1037,
		RePulsePenetrabilityDRM = 1038,
		PulsePenetrabilityDPercent = 1039,
		PulsePenetrabilityDPercentR = 1040,
		RePulsePenetrabilityDPercent = 1041,
		RePulsePenetrabilityDPercentR = 1042,
		PulsePenetrabilityDMR = 1043,
		PulseCritical = 1044,
		PulseCriticalR = 1045,
		PulseCriticalM = 1046,
		PulseCriticalRM = 1047,
		PulseReCriticalM = 1048,
		PulseReCriticalRM = 1049,
		PulseCriticalRate = 1050,
		PulseCriticalRateR = 1051,
		PulseCriticalD = 1052,
		PulseCriticalDR = 1053,
		PulseCriticalDM = 1054,
		PulseCriticalDRM = 1055,
		RePulseCriticalDM = 1056,
		RePulseCriticalDRM = 1057,
		PulseCriticalDPercent = 1058,
		PulseCriticalDPercentR = 1059,
		RePulseCriticalDPercent = 1060,
		RePulseCriticalDPercentR = 1061,
		PulseCriticalDMR = 1062,
		PulseShieldD = 1063,
		PulseShieldDR = 1064,
		PulseShieldDM = 1065,
		PulseShieldDRM = 1066,
		RePulseShieldDM = 1067,
		RePulseShieldDRM = 1068,
		PulseHit = 1069,
		PulseDodgeHit = 1070,
		PulseHitM = 1071,
		PulseHitRM = 1072,
		PulseDodgeHitM = 1073,
		PulseDodgeHitRM = 1074,
		PulseHitRate = 1075,
		PulseDodgeHitRate = 1076,
		PulseRange = 1077,
		PulseRangeM = 1078,
		PulseRangeRM = 1079,
		PlasmaKineticD = 1080,
		PlasmaThermalD = 1081,
		PlasmaNuclearD = 1082,
		PlasmaElectricArcD = 1083,
		PlasmaFreezeD = 1084,
		PlasmaOpticalRadiationD = 1085,
		PlasmaDarkCorrosionD = 1086,
		PlasmaKineticDM = 1087,
		PlasmaKineticDRM = 1088,
		PlasmaThermalDM = 1089,
		PlasmaThermalDRM = 1090,
		PlasmaNuclearDM = 1091,
		PlasmaNuclearDRM = 1092,
		PlasmaElectricArcDM = 1093,
		PlasmaElectricArcDRM = 1094,
		PlasmaFreezeDM = 1095,
		PlasmaFreezeDRM = 1096,
		PlasmaOpticalRadiationDM = 1097,
		PlasmaOpticalRadiationDRM = 1098,
		PlasmaDarkCorrosionDM = 1099,
		PlasmaDarkCorrosionDRM = 1100,
		PlasmaDM = 1101,
		PlasmaDRM = 1102,
		PlasmaDR = 1103,
		RePlasmaDM = 1104,
		RePlasmaDRM = 1105,
		PlasmaPenetrability = 1106,
		PlasmaPenetrabilityR = 1107,
		PlasmaPenetrabilityM = 1108,
		PlasmaPenetrabilityRM = 1109,
		RePlasmaPenetrabilityM = 1110,
		RePlasmaPenetrabilityRM = 1111,
		PlasmaPenetrabilityRate = 1112,
		PlasmaPenetrabilityRateR = 1113,
		PlasmaPenetrabilityD = 1114,
		PlasmaPenetrabilityDR = 1115,
		PlasmaPenetrabilityDM = 1116,
		PlasmaPenetrabilityDRM = 1117,
		RePlasmaPenetrabilityDM = 1118,
		RePlasmaPenetrabilityDRM = 1119,
		PlasmaPenetrabilityDPercent = 1120,
		PlasmaPenetrabilityDPercentR = 1121,
		RePlasmaPenetrabilityDPercent = 1122,
		RePlasmaPenetrabilityDPercentR = 1123,
		PlasmaPenetrabilityDMR = 1124,
		PlasmaCritical = 1125,
		PlasmaCriticalR = 1126,
		PlasmaCriticalM = 1127,
		PlasmaCriticalRM = 1128,
		PlasmaReCriticalM = 1129,
		PlasmaReCriticalRM = 1130,
		PlasmaCriticalRate = 1131,
		PlasmaCriticalRateR = 1132,
		PlasmaCriticalD = 1133,
		PlasmaCriticalDR = 1134,
		PlasmaCriticalDM = 1135,
		PlasmaCriticalDRM = 1136,
		RePlasmaCriticalDM = 1137,
		RePlasmaCriticalDRM = 1138,
		PlasmaCriticalDPercent = 1139,
		PlasmaCriticalDPercentR = 1140,
		RePlasmaCriticalDPercent = 1141,
		RePlasmaCriticalDPercentR = 1142,
		PlasmaCriticalDMR = 1143,
		PlasmaShieldD = 1144,
		PlasmaShieldDR = 1145,
		PlasmaShieldDM = 1146,
		PlasmaShieldDRM = 1147,
		RePlasmaShieldDM = 1148,
		RePlasmaShieldDRM = 1149,
		PlasmaHit = 1150,
		PlasmaDodgeHit = 1151,
		PlasmaHitM = 1152,
		PlasmaHitRM = 1153,
		PlasmaDodgeHitM = 1154,
		PlasmaDodgeHitRM = 1155,
		PlasmaHitRate = 1156,
		PlasmaDodgeHitRate = 1157,
		PlasmaRange = 1158,
		PlasmaRangeM = 1159,
		PlasmaRangeRM = 1160,
		TacticsGrenadeKineticD = 1161,
		TacticsGrenadeThermalD = 1162,
		TacticsGrenadeNuclearD = 1163,
		TacticsGrenadeElectricArcD = 1164,
		TacticsGrenadeFreezeD = 1165,
		TacticsGrenadeOpticalRadiationD = 1166,
		TacticsGrenadeDarkCorrosionD = 1167,
		TacticsGrenadeKineticDM = 1168,
		TacticsGrenadeKineticDRM = 1169,
		TacticsGrenadeThermalDM = 1170,
		TacticsGrenadeThermalDRM = 1171,
		TacticsGrenadeNuclearDM = 1172,
		TacticsGrenadeNuclearDRM = 1173,
		TacticsGrenadeElectricArcDM = 1174,
		TacticsGrenadeElectricArcDRM = 1175,
		TacticsGrenadeFreezeDM = 1176,
		TacticsGrenadeFreezeDRM = 1177,
		TacticsGrenadeOpticalRadiationDM = 1178,
		TacticsGrenadeOpticalRadiationDRM = 1179,
		TacticsGrenadeDarkCorrosionDM = 1180,
		TacticsGrenadeDarkCorrosionDRM = 1181,
		TacticsGrenadeDM = 1182,
		TacticsGrenadeDRM = 1183,
		TacticsGrenadeDR = 1184,
		ReTacticsGrenadeDM = 1185,
		ReTacticsGrenadeDRM = 1186,
		TacticsGrenadePenetrability = 1187,
		TacticsGrenadePenetrabilityR = 1188,
		TacticsGrenadePenetrabilityM = 1189,
		TacticsGrenadePenetrabilityRM = 1190,
		ReTacticsGrenadePenetrabilityM = 1191,
		ReTacticsGrenadePenetrabilityRM = 1192,
		TacticsGrenadePenetrabilityRate = 1193,
		TacticsGrenadePenetrabilityRateR = 1194,
		TacticsGrenadePenetrabilityD = 1195,
		TacticsGrenadePenetrabilityDR = 1196,
		TacticsGrenadePenetrabilityDM = 1197,
		TacticsGrenadePenetrabilityDRM = 1198,
		ReTacticsGrenadePenetrabilityDM = 1199,
		ReTacticsGrenadePenetrabilityDRM = 1200,
		TacticsGrenadePenetrabilityDP = 1201,
		TacticsGrenadePenetrabilityDPR = 1202,
		ReTacticsGrenadePenetrabilityDP = 1203,
		ReTacticsGrenadePenetrabilityDPR = 1204,
		TacticsGrenadePenetrabilityDMR = 1205,
		TacticsGrenadeCritical = 1206,
		TacticsGrenadeCriticalR = 1207,
		TacticsGrenadeCriticalM = 1208,
		TacticsGrenadeCriticalRM = 1209,
		TacticsGrenadeReCriticalM = 1210,
		TacticsGrenadeReCriticalRM = 1211,
		TacticsGrenadeCriticalRate = 1212,
		TacticsGrenadeCriticalRateR = 1213,
		TacticsGrenadeCriticalD = 1214,
		TacticsGrenadeCriticalDR = 1215,
		TacticsGrenadeCriticalDM = 1216,
		TacticsGrenadeCriticalDRM = 1217,
		ReTacticsGrenadeCriticalDM = 1218,
		ReTacticsGrenadeCriticalDRM = 1219,
		TacticsGrenadeCriticalDPercent = 1220,
		TacticsGrenadeCriticalDPercentR = 1221,
		ReTacticsGrenadeCriticalDPercent = 1222,
		ReTacticsGrenadeCriticalDPercentR = 1223,
		TacticsGrenadeCriticalDMR = 1224,
		TacticsGrenadeShieldD = 1225,
		TacticsGrenadeShieldDR = 1226,
		TacticsGrenadeShieldDM = 1227,
		TacticsGrenadeShieldDRM = 1228,
		ReTacticsGrenadeShieldDM = 1229,
		ReTacticsGrenadeShieldDRM = 1230,
		TacticsGrenadeHit = 1231,
		TacticsGrenadeDodgeHit = 1232,
		TacticsGrenadeHitM = 1233,
		TacticsGrenadeHitRM = 1234,
		TacticsGrenadeDodgeHitM = 1235,
		TacticsGrenadeDodgeHitRM = 1236,
		TacticsGrenadeHitRate = 1237,
		TacticsGrenadeDodgeHitRate = 1238,
		TacticsGrenadeRange = 1239,
		TacticsGrenadeRangeM = 1240,
		TacticsGrenadeRangeRM = 1241,
		ArmedUAVKineticD = 1242,
		ArmedUAVThermalD = 1243,
		ArmedUAVNuclearD = 1244,
		ArmedUAVElectricArcD = 1245,
		ArmedUAVFreezeD = 1246,
		ArmedUAVOpticalRadiationD = 1247,
		ArmedUAVDarkCorrosionD = 1248,
		ArmedUAVKineticDM = 1249,
		ArmedUAVKineticDRM = 1250,
		ArmedUAVThermalDM = 1251,
		ArmedUAVThermalDRM = 1252,
		ArmedUAVNuclearDM = 1253,
		ArmedUAVNuclearDRM = 1254,
		ArmedUAVElectricArcDM = 1255,
		ArmedUAVElectricArcDRM = 1256,
		ArmedUAVFreezeDM = 1257,
		ArmedUAVFreezeDRM = 1258,
		ArmedUAVOpticalRadiationDM = 1259,
		ArmedUAVOpticalRadiationDRM = 1260,
		ArmedUAVDarkCorrosionDM = 1261,
		ArmedUAVDarkCorrosionDRM = 1262,
		ArmedUAVDM = 1263,
		ArmedUAVDRM = 1264,
		ArmedUAVDR = 1265,
		ReArmedUAVDM = 1266,
		ReArmedUAVDRM = 1267,
		ArmedUAVPenetrability = 1268,
		ArmedUAVPenetrabilityR = 1269,
		ArmedUAVPenetrabilityM = 1270,
		ArmedUAVPenetrabilityRM = 1271,
		ReArmedUAVPenetrabilityM = 1272,
		ReArmedUAVPenetrabilityRM = 1273,
		ArmedUAVPenetrabilityRate = 1274,
		ArmedUAVPenetrabilityRateR = 1275,
		ArmedUAVPenetrabilityD = 1276,
		ArmedUAVPenetrabilityDR = 1277,
		ArmedUAVPenetrabilityDM = 1278,
		ArmedUAVPenetrabilityDRM = 1279,
		ReArmedUAVPenetrabilityDM = 1280,
		ReArmedUAVPenetrabilityDRM = 1281,
		ArmedUAVPenetrabilityDPercent = 1282,
		ArmedUAVPenetrabilityDPercentR = 1283,
		ReArmedUAVPenetrabilityDPercent = 1284,
		ReArmedUAVPenetrabilityDPercentR = 1285,
		ArmedUAVPenetrabilityDMR = 1286,
		ArmedUAVCritical = 1287,
		ArmedUAVCriticalR = 1288,
		ArmedUAVCriticalM = 1289,
		ArmedUAVCriticalRM = 1290,
		ArmedUAVReCriticalM = 1291,
		ArmedUAVReCriticalRM = 1292,
		ArmedUAVCriticalRate = 1293,
		ArmedUAVCriticalRateR = 1294,
		ArmedUAVCriticalD = 1295,
		ArmedUAVCriticalDR = 1296,
		ArmedUAVCriticalDM = 1297,
		ArmedUAVCriticalDRM = 1298,
		ReArmedUAVCriticalDM = 1299,
		ReArmedUAVCriticalDRM = 1300,
		ArmedUAVCriticalDPercent = 1301,
		ArmedUAVCriticalDPercentR = 1302,
		ReArmedUAVCriticalDPercent = 1303,
		ReArmedUAVCriticalDPercentR = 1304,
		ArmedUAVCriticalDMR = 1305,
		ArmedUAVShieldD = 1306,
		ArmedUAVShieldDR = 1307,
		ArmedUAVShieldDM = 1308,
		ArmedUAVShieldDRM = 1309,
		ReArmedUAVShieldDM = 1310,
		ReArmedUAVShieldDRM = 1311,
		ArmedUAVHit = 1312,
		ArmedUAVDodgeHit = 1313,
		ArmedUAVHitM = 1314,
		ArmedUAVHitRM = 1315,
		ArmedUAVDodgeHitM = 1316,
		ArmedUAVDodgeHitRM = 1317,
		ArmedUAVHitRate = 1318,
		ArmedUAVDodgeHitRate = 1319,
		ArmedUAVRange = 1320,
		ArmedUAVRangeM = 1321,
		ArmedUAVRangeRM = 1322,
		BurstUAVKineticD = 1323,
		BurstUAVThermalD = 1324,
		BurstUAVNuclearD = 1325,
		BurstUAVElectricArcD = 1326,
		BurstUAVFreezeD = 1327,
		BurstUAVOpticalRadiationD = 1328,
		BurstUAVDarkCorrosionD = 1329,
		BurstUAVKineticDM = 1330,
		BurstUAVKineticDRM = 1331,
		BurstUAVThermalDM = 1332,
		BurstUAVThermalDRM = 1333,
		BurstUAVNuclearDM = 1334,
		BurstUAVNuclearDRM = 1335,
		BurstUAVElectricArcDM = 1336,
		BurstUAVElectricArcDRM = 1337,
		BurstUAVFreezeDM = 1338,
		BurstUAVFreezeDRM = 1339,
		BurstUAVOpticalRadiationDM = 1340,
		BurstUAVOpticalRadiationDRM = 1341,
		BurstUAVDarkCorrosionDM = 1342,
		BurstUAVDarkCorrosionDRM = 1343,
		BurstUAVDM = 1344,
		BurstUAVDRM = 1345,
		BurstUAVDR = 1346,
		ReBurstUAVDM = 1347,
		ReBurstUAVDRM = 1348,
		BurstUAVPenetrability = 1349,
		BurstUAVPenetrabilityR = 1350,
		BurstUAVPenetrabilityM = 1351,
		BurstUAVPenetrabilityRM = 1352,
		ReBurstUAVPenetrabilityM = 1353,
		ReBurstUAVPenetrabilityRM = 1354,
		BurstUAVPenetrabilityRate = 1355,
		BurstUAVPenetrabilityRateR = 1356,
		BurstUAVPenetrabilityD = 1357,
		BurstUAVPenetrabilityDR = 1358,
		BurstUAVPenetrabilityDM = 1359,
		BurstUAVPenetrabilityDRM = 1360,
		ReBurstUAVPenetrabilityDM = 1361,
		ReBurstUAVPenetrabilityDRM = 1362,
		BurstUAVPenetrabilityDPercent = 1363,
		BurstUAVPenetrabilityDPercentR = 1364,
		ReBurstUAVPenetrabilityDPercent = 1365,
		ReBurstUAVPenetrabilityDPercentR = 1366,
		BurstUAVPenetrabilityDMR = 1367,
		BurstUAVCritical = 1368,
		BurstUAVCriticalR = 1369,
		BurstUAVCriticalM = 1370,
		BurstUAVCriticalRM = 1371,
		BurstUAVReCriticalM = 1372,
		BurstUAVReCriticalRM = 1373,
		BurstUAVCriticalRate = 1374,
		BurstUAVCriticalRateR = 1375,
		BurstUAVCriticalD = 1376,
		BurstUAVCriticalDR = 1377,
		BurstUAVCriticalDM = 1378,
		BurstUAVCriticalDRM = 1379,
		ReBurstUAVCriticalDM = 1380,
		ReBurstUAVCriticalDRM = 1381,
		BurstUAVCriticalDPercent = 1382,
		BurstUAVCriticalDPercentR = 1383,
		ReBurstUAVCriticalDPercent = 1384,
		ReBurstUAVCriticalDPercentR = 1385,
		BurstUAVCriticalDMR = 1386,
		BurstUAVShieldD = 1387,
		BurstUAVShieldDR = 1388,
		BurstUAVShieldDM = 1389,
		BurstUAVShieldDRM = 1390,
		ReBurstUAVShieldDM = 1391,
		ReBurstUAVShieldDRM = 1392,
		BurstUAVHit = 1393,
		BurstUAVDodgeHit = 1394,
		BurstUAVHitM = 1395,
		BurstUAVHitRM = 1396,
		BurstUAVDodgeHitM = 1397,
		BurstUAVDodgeHitRM = 1398,
		BurstUAVHitRate = 1399,
		BurstUAVDodgeHitRate = 1400,
		BurstUAVRange = 1401,
		BurstUAVRangeM = 1402,
		BurstUAVRangeRM = 1403,
		MineKineticD = 1404,
		MineThermalD = 1405,
		MineNuclearD = 1406,
		MineElectricArcD = 1407,
		MineFreezeD = 1408,
		MineOpticalRadiationD = 1409,
		MineDarkCorrosionD = 1410,
		MineKineticDM = 1411,
		MineKineticDRM = 1412,
		MineThermalDM = 1413,
		MineThermalDRM = 1414,
		MineNuclearDM = 1415,
		MineNuclearDRM = 1416,
		MineElectricArcDM = 1417,
		MineElectricArcDRM = 1418,
		MineFreezeDM = 1419,
		MineFreezeDRM = 1420,
		MineOpticalRadiationDM = 1421,
		MineOpticalRadiationDRM = 1422,
		MineDarkCorrosionDM = 1423,
		MineDarkCorrosionDRM = 1424,
		MineDM = 1425,
		MineDRM = 1426,
		MineDR = 1427,
		ReMineDM = 1428,
		ReMineDRM = 1429,
		MinePenetrability = 1430,
		MinePenetrabilityR = 1431,
		MinePenetrabilityM = 1432,
		MinePenetrabilityRM = 1433,
		ReMinePenetrabilityM = 1434,
		ReMinePenetrabilityRM = 1435,
		MinePenetrabilityRate = 1436,
		MinePenetrabilityRateR = 1437,
		MinePenetrabilityD = 1438,
		MinePenetrabilityDR = 1439,
		MinePenetrabilityDM = 1440,
		MinePenetrabilityDRM = 1441,
		ReMinePenetrabilityDM = 1442,
		ReMinePenetrabilityDRM = 1443,
		MinePenetrabilityDPercent = 1444,
		MinePenetrabilityDPercentR = 1445,
		ReMinePenetrabilityDPercent = 1446,
		ReMinePenetrabilityDPercentR = 1447,
		MinePenetrabilityDMR = 1448,
		MineCritical = 1449,
		MineCriticalR = 1450,
		MineCriticalM = 1451,
		MineCriticalRM = 1452,
		MineReCriticalM = 1453,
		MineReCriticalRM = 1454,
		MineCriticalRate = 1455,
		MineCriticalRateR = 1456,
		MineCriticalD = 1457,
		MineCriticalDR = 1458,
		MineCriticalDM = 1459,
		MineCriticalDRM = 1460,
		ReMineCriticalDM = 1461,
		ReMineCriticalDRM = 1462,
		MineCriticalDPercent = 1463,
		MineCriticalDPercentR = 1464,
		ReMineCriticalDPercent = 1465,
		ReMineCriticalDPercentR = 1466,
		MineCriticalDMR = 1467,
		MineShieldD = 1468,
		MineShieldDR = 1469,
		MineShieldDM = 1470,
		MineShieldDRM = 1471,
		ReMineShieldDM = 1472,
		ReMineShieldDRM = 1473,
		MineHit = 1474,
		MineDodgeHit = 1475,
		MineHitM = 1476,
		MineHitRM = 1477,
		MineDodgeHitM = 1478,
		MineDodgeHitRM = 1479,
		MineHitRate = 1480,
		MineDodgeHitRate = 1481,
		MineRange = 1482,
		MineRangeM = 1483,
		MineRangeRM = 1484,
		ArtilleryKineticD = 1485,
		ArtilleryThermalD = 1486,
		ArtilleryNuclearD = 1487,
		ArtilleryElectricArcD = 1488,
		ArtilleryFreezeD = 1489,
		ArtilleryOpticalRadiationD = 1490,
		ArtilleryDarkCorrosionD = 1491,
		ArtilleryKineticDM = 1492,
		ArtilleryKineticDRM = 1493,
		ArtilleryThermalDM = 1494,
		ArtilleryThermalDRM = 1495,
		ArtilleryNuclearDM = 1496,
		ArtilleryNuclearDRM = 1497,
		ArtilleryElectricArcDM = 1498,
		ArtilleryElectricArcDRM = 1499,
		ArtilleryFreezeDM = 1500,
		ArtilleryFreezeDRM = 1501,
		ArtilleryOpticalRadiationDM = 1502,
		ArtilleryOpticalRadiationDRM = 1503,
		ArtilleryDarkCorrosionDM = 1504,
		ArtilleryDarkCorrosionDRM = 1505,
		MissileKineticD = 1506,
		MissileThermalD = 1507,
		MissileNuclearD = 1508,
		MissileElectricArcD = 1509,
		MissileFreezeD = 1510,
		MissileOpticalRadiationD = 1511,
		MissileDarkCorrosionD = 1512,
		MissileKineticDM = 1513,
		MissileKineticDRM = 1514,
		MissileThermalDM = 1515,
		MissileThermalDRM = 1516,
		MissileNuclearDM = 1517,
		MissileNuclearDRM = 1518,
		MissileElectricArcDM = 1519,
		MissileElectricArcDRM = 1520,
		MissileFreezeDM = 1521,
		MissileFreezeDRM = 1522,
		MissileOpticalRadiationDM = 1523,
		MissileOpticalRadiationDRM = 1524,
		MissileDarkCorrosionDM = 1525,
		MissileDarkCorrosionDRM = 1526,
		LaserKineticD = 1527,
		LaserThermalD = 1528,
		LaserNuclearD = 1529,
		LaserElectricArcD = 1530,
		LaserFreezeD = 1531,
		LaserOpticalRadiationD = 1532,
		LaserDarkCorrosionD = 1533,
		LaserKineticDM = 1534,
		LaserKineticDRM = 1535,
		LaserThermalDM = 1536,
		LaserThermalDRM = 1537,
		LaserNuclearDM = 1538,
		LaserNuclearDRM = 1539,
		LaserElectricArcDM = 1540,
		LaserElectricArcDRM = 1541,
		LaserFreezeDM = 1542,
		LaserFreezeDRM = 1543,
		LaserOpticalRadiationDM = 1544,
		LaserOpticalRadiationDRM = 1545,
		LaserDarkCorrosionDM = 1546,
		LaserDarkCorrosionDRM = 1547,
		GrenadeKineticD = 1548,
		GrenadeThermalD = 1549,
		GrenadeNuclearD = 1550,
		GrenadeElectricArcD = 1551,
		GrenadeFreezeD = 1552,
		GrenadeOpticalRadiationD = 1553,
		GrenadeDarkCorrosionD = 1554,
		GrenadeKineticDM = 1555,
		GrenadeKineticDRM = 1556,
		GrenadeThermalDM = 1557,
		GrenadeThermalDRM = 1558,
		GrenadeNuclearDM = 1559,
		GrenadeNuclearDRM = 1560,
		GrenadeElectricArcDM = 1561,
		GrenadeElectricArcDRM = 1562,
		GrenadeFreezeDM = 1563,
		GrenadeFreezeDRM = 1564,
		GrenadeOpticalRadiationDM = 1565,
		GrenadeOpticalRadiationDRM = 1566,
		GrenadeDarkCorrosionDM = 1567,
		GrenadeDarkCorrosionDRM = 1568,
		UAVKineticD = 1569,
		UAVThermalD = 1570,
		UAVNuclearD = 1571,
		UAVElectricArcD = 1572,
		UAVFreezeD = 1573,
		UAVOpticalRadiationD = 1574,
		UAVDarkCorrosionD = 1575,
		UAVKineticDM = 1576,
		UAVKineticDRM = 1577,
		UAVThermalDM = 1578,
		UAVThermalDRM = 1579,
		UAVNuclearDM = 1580,
		UAVNuclearDRM = 1581,
		UAVElectricArcDM = 1582,
		UAVElectricArcDRM = 1583,
		UAVFreezeDM = 1584,
		UAVFreezeDRM = 1585,
		UAVOpticalRadiationDM = 1586,
		UAVOpticalRadiationDRM = 1587,
		UAVDarkCorrosionDM = 1588,
		UAVDarkCorrosionDRM = 1589,
		EffectiveD = 1590,
		CloseRangeD = 1591,
		LongRangeD = 1592,
		DecelerationR = 1593,
		BurningR = 1594,
		ImprisonR = 1595,
		SilenceR = 1596,
		DizzinessR = 1597,
		EnergyPowerCostAdd = 1598,
		EnergyPowerCostM = 1599,
		EnergyPowerCostRM = 1600,
		SuperMagneticCostAdd = 1601,
		SuperMagneticCostM = 1602,
		SuperMagneticCostRM = 1603,
		SkillCostAdd = 1604,
		SkillCostM = 1605,
		SkillCostRM = 1606,
		ImprisonAttr = 1607,
		SilenceAttr = 1608,
		DizzinessAttr = 1609,
		HPRecoveryCurb = 1610,
		ShieldRecoveryCurb = 1611,
		Invincible = 1612,
		peerlessTopLimit = 1613,
		peerlessCost = 1614,
		stealth = 1615,
		velocityMaxZ = 10001,
		reverseVelocityMaxZ = 10002,
		velocityMaxX = 10003,
		reverseVelocityMaxX = 10004,
		velocityMaxY = 10005,
		reverseVelocityMaxY = 10006,
		accelerationZ = 10007,
		reverseAccelerationZ = 10008,
		accelerationX = 10009,
		reverseAccelerationX = 10010,
		accelerationY = 10011,
		reverseAccelerationY = 10012,
		resistanceAccelerationZ = 10013,
		resistanceAccelerationX = 10014,
		resistanceAccelerationY = 10015,
		angularVelocityMaxX = 10016,
		angularVelocityMaxY = 10017,
		angularVelocityMaxZ = 10018,
		angularAcceleration = 10019,
		resistanceAngularAcceleration = 10020,
		leapVelocityStart = 10021,
		leapAcceleration = 10022,
		leapVelocityMax = 10023,
		leapReverseAcceleration = 10024,
		leapVelocityEnd = 10025,
		angularTiltMaxX = 10026,
		angularTiltMaxY = 10027,
		angularTiltMaxZ = 10028,
		cruiseVelocitymaxz = 10029,
		cruiseReversevelocitymaxz = 10030,
		cruiseVelocitymaxx = 10031,
		cruiseReversevelocitymaxx = 10032,
		cruiseVelocitymaxy = 10033,
		cruiseReversevelocitymaxy = 10034,
		cruiseAccelerationz = 10035,
		cruiseReverseaccelerationz = 10036,
		cruiseAccelerationx = 10037,
		cruiseReverseaccelerationx = 10038,
		cruiseAccelerationy = 10039,
		cruiseReverseaccelerationy = 10040,
		cruiseResistanceaccelerationz = 10041,
		cruiseResistanceaccelerationx = 10042,
		cruiseResistanceaccelerationy = 10043,
		cruiseAngularvelocitymaxx = 10044,
		cruiseAngularvelocitymaxy = 10045,
		cruiseAngularvelocitymaxz = 10046,
		cruiseAngularacceleration = 10047,
		cruiseResistanceAngleDecelerate = 10048,
		cruiseLeapvelocitystart = 10049,
		cruiseLeapacceleration = 10050,
		cruiseLeapvelocitymax = 10051,
		cruiseLeapreverseacceleration = 10052,
		cruiseLeapvelocityend = 10053,
		cruiseAngulartiltmaxx = 10054,
		cruiseAngulartiltmaxy = 10055,
		cruiseAngulartiltmaxz = 10056,
		overloadVelocitymaxz = 10057,
		overloadReversevelocitymaxz = 10058,
		overloadVelocitymaxx = 10059,
		overloadReversevelocitymaxx = 10060,
		overloadVelocitymaxy = 10061,
		overloadReversevelocitymaxy = 10062,
		overloadAccelerationz = 10063,
		overloadReverseaccelerationz = 10064,
		overloadAccelerationx = 10065,
		overloadReverseaccelerationx = 10066,
		overloadAccelerationy = 10067,
		overloadReverseaccelerationy = 10068,
		overloadResistanceaccelerationz = 10069,
		overloadResistanceaccelerationx = 10070,
		overloadResistanceaccelerationy = 10071,
		overloadAngularvelocitymaxx = 10072,
		overloadAngularvelocitymaxy = 10073,
		overloadAngularvelocitymaxz = 10074,
		overloadAngularacceleration = 10075,
		overloadResistanceAngleRetard = 10076,
		overloadAngulartiltmaxx = 10077,
		overloadAngulartiltmaxy = 10078,
		overloadAngulartiltmaxz = 10079,
		overloadPowercostefficiency = 10080,
		MagazineC = 11001,
		MagazineLT = 11002,
		AmmoCPS = 11003,
		MissileH = 11004,
		MissileHRT = 11005,
		GuidedMissileCPS = 11006,
		HeatC = 11007,
		CooldownT = 11008,
		CooldownR = 11009,
		SaftyValveV = 11010,
		HeatAPS = 11011,
	}

	public enum EffectType
	{
		Damage = 0,
		TriggerAnomaly = 1,
		RecoverHP = 2,
		DotDamage = 3,
		RecoverShield = 4,
		RecoverPower = 5,
	}

	public enum BuffEvent
	{
		NoneBuffEvent = 0,
		Overload = 1,
		WeaponUse = 2,
		KillTarget = 3,
		OnHurt = 4,
	}

	public enum KAttributeType
	{
		atInvalid = 0,
		atMaxHP = 1,
		atMaxHPPP = 2,
		atMaxMP = 3,
		atMaxMPPP = 4,
		atAttack = 5,
		atAttackPP = 6,
		atDefence = 7,
		atDefencePP = 8,
		atMiss = 9,
		atMissPP = 10,
		atNotMiss = 11,
		atNotMissPP = 12,
		atCrit = 13,
		atCritPP = 14,
		atNotCrit = 15,
		atNotCritPP = 16,
		atCritHurt = 17,
		atNotCritHurt = 18,
		atBlock = 25,
		atBlockPP = 26,
		atNotBlock = 27,
		atNotBlockPP = 28,
		atCritHurtPP = 33,
		atNotCritHurtPP = 34,
		atMaxAnger = 36,
		atMaxAngerPP = 37,
		atDamageCof = 49,
		atAttackCof = 50,
		atRecoverHP = 52,
		atRecoverHPPP = 53,
		atRecoverMP = 54,
		atRecoverMPPP = 55,
		atRecoverAnger = 62,
		atRecoverAngerPP = 63,
		atBeHitRecoverMP = 64,
		atBeHitRecoverMPPP = 65,
		atNumAtrribute = 200,
		atMoveSpeedBase = 201,
		atMoveSpeed = 202,
		atMoveSpeedPP = 203,
		atCurrentHP = 204,
		atCurrentHPPP = 206,
		atCurrentMP = 207,
		atCurrentMPPP = 208,
		atCurrentAnger = 215,
		atCurrentAngerPP = 216,
		atForbitMove = 209,
		atForbitSkill = 210,
		atCostSkillMPValue = 211,
		atInvincible = 212,
		atExpPP = 213,
		atVisible = 214,
		atResitForceMove = 217,
		atResitForbitMove = 219,
		atResitForbitSkill = 220,
		atStun = 221,
		atResitStun = 222,
		atBlind = 223,
		atResitBlind = 224,
		atArmorBreak = 225,
		atResitArmorBreak = 226,
		atNoDamage = 227,
		atABSDamage = 228,
		atNotABSDamage = 229,
		atTotal = 230,
	}

	public enum KConstDefine
	{
		cdNoTeamWinID = 255,
		cdMaxHeroLevel = 60,
		cdRoomPasswordMaxLen = 32,
		cdMaxItemBaseAttrCount = 6,
		cdLadderRoomCountDownSeconds = 5,
		cdMaxEventParamCount = 3,
		cdInvalidFelllowshipGroupID = 250,
		cdMaxVIPLevel = 10,
		cdMaxQuestEventCount = 2,
		cdQuestParamCount = 8,
		cdMaxAcceptQuestCount = 25,
		cdShotcutSize = 3,
		cdDefalutBattleTime = 180,
		cdMaxUsingHeroCount = 3,
		cdDefaultTalkDataLength = 512,
		cdMaxLadderTopListMemberCount = 1000,
		cdServerPlatformBegin = 10000,
		cdTestServerID = 9999,
		cdBackgroundRewardItemIdBegin = 100,
		cdBackgroundRewardEquipIdBegin = 10000000,
		cdLadderTopListCountPerPage = 10,
		cdPlayerPageSize = 25,
		cdMaxMapEventCout = 4,
		cdDefaultGroupID = 1,
	}

	public enum KGender
	{
		gNone = 0,
		gMale = 1,
		gFemale = 2,
	}

	public enum KChatType
	{
		trInvalid = 0,
		trWhisper = 1,
		trTeam = 2,
		trHorn = 3,
		trSystem = 4,
		trWorld = 5,
		trClub = 6,
		trTeamNotice = 7,
		trGlobalSys = 8,
		trGmAnnounce = 9,
		trTotal = 10,
	}

	public enum KPlayerEvent
	{
		peInvalid = 0,
		peAcceptQuest = 1,
		peNPCDie = 2,
		peNpcWaveDie = 3,
		peClickNPC = 4,
		peTotal = 5,
	}

	public enum KMissionResultCode
	{
		qrcInvalid = 0,
		qrcSuccess = 1,
		qrcFailed = 2,
	}

	public enum KMissionType
	{
		qtInvalid = 0,
		qtMainMission = 1,
		qtSubLineMission = 2,
		qtLoopMission = 3,
		qtTianxiadashiMission = 4,
		qtWantedMission = 5,
		qtGuildMission = 6,
		qtOfficialMission = 7,
	}

	public enum KMapType
	{
		mapInvalid = 0,
		mapMainCity = 1,
		mapSpaceStation = 2,
		mapNearGround = 3,
		mapDeepSpace = 4,
		mapPVE = 5,
		mapCountryWar = 6,
		mapAnnihilatePVE = 7,
		mapDefencePVE = 8,
		mapEscapePVE = 9,
		mapTeam = 10,
		mutilTeamMap = 11,
		mapTotal = 12,
	}

	public enum KMapPathType
	{
		KMapPath_Invalid = 0,
		KMapPath_Ground = 1,
		KMapPath_Space = 2,
	}

	public enum KNumMoneyType
	{
		none = 0,
		money1 = 1,
		money2 = 2,
		emotTotal = 3,
	}

	public enum KGateWayHandShakeCode
	{
		ghcHandshakeSucceed = 1,
		ghcGatewayVersionError = 2,
		ghcGameWorldMaintenance = 3,
		ghcAccountSystemLost = 4,
		ghcGameWorldVersionError = 5,
		ghcReconnectError = 6,
		ghcCenterTypeError = 7,
	}

	public enum KCreateRoleRespondCode
	{
		eCreateRoleSucceed = 1,
		eCreateRoleNameAlreadyExist = 2,
		eCreateRoleInvalidRoleName = 3,
		eCreateRoleNameTooLong = 4,
		eCreateRoleNameTooShort = 5,
		eCreateRoleUnableToCreate = 6,
	}

	public enum KDeleteRoleRespondCode
	{
		eDeleteRoleSucceed = 1,
		eDeleteRoleDelay = 2,
		eDeleteRoleFreezeRole = 3,
		eDeleteRoleUnknownError = 4,
	}

	public enum KUndoDelRoleRespondCode
	{
		eUndoDelRoleSucceed = 1,
		eUndoDelRoleUnknownError = 2,
	}

	public enum KGameLoginRespondCode
	{
		eGameLoginSucceed = 1,
		eGameLoginSystemMaintenance = 2,
		eGameLoginQueueWait = 3,
		eGameLoginOverload = 4,
		eGameLoginRoleFreeze = 5,
		eGameLoginRoleCenterSwitching = 6,
		eGameLoginRoleChangeAccount = 7,
		eGameLoginRoleAlreadyDelete = 8,
		eGameLoginUnknownError = 9,
	}

	public enum KMailType
	{
		mtSystemMail = 1,
		mtGlobalMail = 2,
	}

	public enum KAttackEvent
	{
		aeNormal = 0,
		aeMiss = 1,
		aeCrit = 2,
		aeBlock = 4,
		aeNoDamage = 8,
		aeReboundDamage = 16,
	}

	public enum KSkillTargetType
	{
		sttNone = 0,
		sttObj = 1,
		sttPos = 2,
		sttSelf = 3,
	}

	public enum KTriggerStartPos
	{
		tspNone = 0,
		tspObj = 1,
		tspPos = 2,
		tspSelf = 3,
		tspMaster = 4,
	}

	public enum KEffectArea
	{
		eaNone = 0,
		eaSingle = 1,
		eaCirc = 2,
		eaFan = 3,
		eaLine = 4,
	}

	public enum KEffectTarget
	{
		etEnemy = 0,
		etFriend = 1,
		etMine = 2,
		etSelf = 3,
		etMonster = 4,
		etSameTeam = 5,
		etSPPlayer = 6,
		etSPMonster = 7,
		etSPEliteMonster = 8,
		etSPPlotMonster = 9,
		etSPBoss = 10,
		etSPSpecialMonster = 11,
		etSPWorldBoss = 12,
		etSPGeneral = 13,
		etSPOfflinePlayer = 14,
		etSPBuilding = 15,
		etSPBiaoChe = 16,
		etSPHeroPartyBoss = 17,
		etSPCampFlag = 18,
		etSPGuard = 19,
		etSPProtege = 20,
		etSPPlayerOrMonster = 21,
		etNeutral = 22,
		etFriendLy = 23,
	}

	public enum KJob
	{
		jobNone = 0,
		JobBlade = 1,
		JobLance = 2,
		JobHammer = 3,
		JobBoxer = 4,
		JobTotal = 4,
	}

	public enum KItemTableType
	{
		ittInvalid = 0,
		ittEquip = 1,
		ittOther = 2,
		ittResource = 3,
		ittWarrior = 4,
		ittTotal = 5,
	}

	public enum KItemQuality
	{
		iqNone = 0,
		iqWhite = 1,
		iqGreen = 2,
		iqBlue = 3,
		iqPurple = 4,
		iqGolden = 5,
		iqOrange = 6,
		iqRed = 7,
		iqEnd = 8,
	}

	public enum KItemBind
	{
		kbNone = 0,
		kbFixBind = 1,
		kbFixNotBind = 2,
		kbAfterWearBind = 3,
		kbAfterTradeBind = 4,
		kbEnd = 5,
	}

	public enum KItemUseSign
	{
		kuNone = 0,
		kuUnuse = kuNone,
		kuUse = 1,
		kuEnd = 2,
	}

	public enum KItemDropSign
	{
		kdNone = 0,
		kdNo = kdNone,
		kdYes = 1,
		kdEnd = 2,
	}

	public enum KItemSellSign
	{
		ksNone = 0,
		ksNo = ksNone,
		ksYes = 1,
		ksEnd = 2,
	}

	public enum KItemBroadcastSign
	{
		kbsNone = 0,
		kbsNo = kbsNone,
		kbsYes = 1,
		kbsEnd = 2,
	}

	public enum KHeroType
	{
		htInvalid = -1,
		htPlayer = 0,
		htNpc = 1,
		htDynamicDecorate = 2,
		htMonster = 3,
		htStarGate = 4,
		htSpaceStation = 5,
		htBeEscortedNpc = 6,
		htEliteMonster1 = 7,
		htEliteMonster2 = 8,
		htEliteMonster3 = 9,
		htPlotMonster = 10,
		htBoss = 11,
		htSpecialMonster = 12,
		htWorldBoss = 13,
		htGeneral = 14,
		htOfflinePlayer = 15,
		htBuilding = 16,
		htPet = 17,
		htBiaoChe = 18,
		htHeroPartyBoss = 19,
		htCampFlag = 20,
		htGuard = 21,
		htProtege = 22,
		htNpcTrrgger = 23,
		htBunker = 24,
		htBattleFieldChest = 25,
		htMonsterChest = 26,
		htSceneChest = 27,
		htSceneGlobalObj = 28,
		htSpellSummonObj = 29,
		htReliveNpc = 30,
		htMissionTrigger = 31,
		htMine = 32,
		htMineDrop = 33,
		htPreicous = 34,
		htDetector = 35,
		htLockChest = 36,
		htRareChestGuard = 37,
		htNormalChest = 38,
		htNormalChestGuard = 39,
		htDisturbor = 40,
	}

	public enum KTriggerType
	{
		kttDefault = 0,
		kttBattlefield = 1,
		kttDetector = 2,
	}

	public enum KForceMoveType
	{
		fmtInvalid = 0,
		fmtJump = 1,
		fmtRush = 2,
		fmtPull = 3,
		fmtBack = 4,
		fmtKeepLength = 5,
		fmtKnockDown = 6,
		fmtKnockFly = 7,
	}

	public enum KForceMoveObj
	{
		fmoInvalid = 0,
		fmoSelf = 1,
		fmoOther = 2,
	}

	public enum KForceMoveDes
	{
		fmdInvalid = 0,
		fmdCaster = 1,
		fmdSkillTarget = 2,
		fmdSkillPos = 3,
	}

	public enum KDropType
	{
		dtInvalid = 0,
		dtEquip = 1,
		dtItem = 2,
		dtMoney = 3,
	}

	public enum KReliveType
	{
		rltInvalid = 0,
		rltJustHero = 1,
		rltMapRule = 2,
	}

	public enum KStlOpCode
	{
		stlFind = 0,
		stlBegin = 1,
		stlNext = 2,
		stlErase = 3,
		stlRemove = 4,
		stlLength = 5,
	}

	public enum KCollectResult
	{
		crInvalid = 0,
		crSuccess = 1,
		crFailed = 2,
	}

	public enum KSceneState
	{
		ssInvalid = 0,
		ssLoading = 1,
		ssCompleteLoading = 2,
		ssFailedLoading = 3,
		ssWaitingClientLoading = 4,
		ssCountDown = 5,
		ssFighting = 6,
		ssWatingDelete = 7,
		ssTotal = 8,
	}

	public enum KEnterPVEResult
	{
		epInvalid = 0,
		epSuccess = 1,
		epFailed = 2,
		epNeedDuplicateToken = 3,
	}

	public enum KModuleType
	{
		mtInvalid = 0,
		mtDefault = 1,
		mtEquip = 2,
		mtGeneral = 3,
		mtHorse = 4,
		mtMeridian = 5,
		mtShenBing = 6,
		mtSkill = 7,
		mtBuff = 9,
		mtBagAdd = 10,
		mtWareHouseAdd = 11,
		mtYangMingAdd = 12,
		mtYiTongTianXia = 13,
		mtGuild = 14,
		mtMagicWeapon = 15,
		mtMantle = 16,
		mtWing = 17,
		mtCollectActivity = 18,
		mtTitle = 19,
		mtAura = 20,
		mtZhiZhuan = 21,
		mtArmor = 22,
		mtDragonSoul = 23,
		mtPlough = 24,
		mtGem = 25,
		mtPrivilege = 26,
		mtFashion = 27,
		mtGeneralSuit = 28,
		mtGuanXian = 29,
		mtEnchant = 30,
		mtForge = 31,
		mtSuitEquip = 32,
		mtTotal = 33,
	}

	public enum KAttributeComputeType
	{
		actAttackSpeed = 1,
		actBashProbability = 2,
	}

	public enum KRefreshLocationType
	{
		rltFix = 1,
		rltRandom = 2,
		rltNearPlayer = 3,
	}

	public enum KRefreshRuleType
	{
		rrtCoolDown = 1,
		rrtTimePoint = 2,
		rrtKillMonsterNum = 3,
	}

	public enum KTriggerFrom
	{
		ktfInvalid = 0,
		ktfActiveSkill = 1,
		ktfPassiveSkill = 2,
		ktfBuff = 3,
	}

	public enum KHitTrigger
	{
		khtDefault = 0,
		khtHitOnce = 1,
		khtHitMulti = 2,
	}

	public enum KGeneralQuality
	{
		gqGreen = 1,
		gqBlue = 2,
		gqPurple = 3,
		gqOrange = 4,
		gqGold = 5,
		gqRed = 6,
		gqTotal = 7,
	}

	public enum KFightEvent
	{
		kfeInvalid = 0,
		kfeTriggerTarget = 1,
		kfeCastTrigger = 2,
		kfeCastTriggerNT = 3,
		kfeTimer = 4,
		kfeAEMiss = 5,
		kfeAECrit = 6,
		kfeAEBlock = 8,
		kfeHit = 9,
		kfeBeHit = 10,
		kfeHp = 11,
		kfeHpPP = 12,
		kfeKill = 13,
		kfeBeKill = 14,
		kfeComboKill = 15,
	}

	public enum KMailCount
	{
		mcPageSize = 9,
	}

	public enum KLoadProtoBufFromDBResult
	{
		lpfdrFailed = 0,
		lpfdrNotData = 1,
		lpfdrSuccess = 2,
	}

	public enum KPVEType
	{
		pveInvalid = 0,
		pveEquip = 1,
		pveResource = 2,
		pveQiBao = 3,
		pveGeneral = 4,
		pveZhenBao = 5,
		pveExp = 6,
		pveVIP = 7,
		pveGuild = 8,
		pveTeam = 9,
		pveZBTX = 10,
		pveTFQX = 11,
	}

	public enum KBuffDropType
	{
		bdtBuff = 1,
		bdtCall = 2,
	}

	public enum PlayerReliveType
	{
		relive_hall = 1,
		relive_pos = 2,
		insitu = 3,
	}

	public enum KSpecialCost
	{
		kscInvalid = 0,
		kscSummon = 1,
		kscBuff = 2,
	}

	public enum KCampType
	{
		kctDefault = 0,
		kctPlayer = 1,
		kctCampA = 2,
		kctCampB = 3,
	}

	public enum KPkMode
	{
		kpmDefault = 0,
		kpmActive = 1,
		kpmPeace = 2,
		kpmTeam = 3,
		kpmGuild = 4,
		kpmGroup = 5,
		kpmTotal = 6,
	}

	public enum KPkModeEx
	{
		kpeSameTeam = 0,
		kpeSameGuild = 1,
		kpeSameGroup = 2,
		kpeTotal = 3,
	}

	public enum KTeamMode
	{
		ktmDefault = 0,
		ktmFreeTeam = 1,
		ktmGuildTeam = 2,
		ktmDuplicateTeam = 3,
	}

	public enum KAIType
	{
		katInvalid = 0,
		katCommon = 1,
		katGeneral = 2,
		katMonster = 3,
		katTest = 4,
		katPVEMonsterAI = 5,
		katEscortAI = 6,
		katAidSummon = 7,
		katBiaoChe = 8,
		katFormation = 9,
		katTrap = 10,
	}

	public enum KAICast
	{
		aicInvalid = 0,
		aicBuffOverlapLT = 1,
		aicBuffOverlapGT = 2,
	}

	public enum KResourceRewardIDType
	{
		rritInvalid = -1,
		rritMoney = 0,
		rritGold = 1,
		rritLijuan = 2,
		rritZuoqijinghua = 3,
		rritBaoshijinghua = 4,
		rritZhenqi = 5,
		rritQunYinHui = 6,
		rritExp = 7,
		rritYueLi = 9,
		rritGuildDonation = 10,
		rritZhanGong = 11,
		rritPrestige = 12,
		rritMedal = 13,
		rritHighMedal = 14,
		rritVipExp = 15,
	}

	public enum KGATEWAY_ERROR_CODE
	{
		gecInvalidAccountInTestMode = 0,
		gecAccountInfoIsNotExist = 1,
		gecPasswdInfoIsNotExist = 2,
		gecTokenIsNotMatch = 3,
	}

	public enum KLimitPlayTimeType
	{
		lpttNoInfo = 0,
		lpttAdult = 1,
		lpttTeenager = 2,
	}

	public enum KKickPlayerType
	{
		kptByRelogin = 0,
		kptByGM = 1,
		kptByLimitPlayTime = 2,
	}

	public enum KCollectObjectType
	{
		cotMission = 1,
		cotNormal = 2,
		cotFeudalFightingFlag = 3,
		cotCampBattleFlag = 4,
		cotFubenBoxFlag = 5,
		cotDropBoxFlag = 6,
		cotTombstone = 7,
		cotGuard = 8,
		cotCollectActivityResource = 9,
		cotCollectCommitResource = 10,
		cotGuildWarFlag = 11,
		cotLuoYanCollectBox = 12,
	}

	public enum KCollectErrorCode
	{
		cecSuccess = 1,
		cecTargetNotExist = 2,
		cecOccupiedByOthers = 3,
		cecTargetTooFarAway = 4,
		cecOthers = 5,
		cecTargetNotAGuard = 10,
		cecGuardNotInWakeState = 11,
		cecCollectActivityLimit = 12,
	}

	public enum KEnterPositionType
	{
		eptIvalide = 0,
		eptPos = 1,
		eptEffect = 2,
		eptPosAndEffect = 3,
	}

	public enum KAnimationType
	{
		amtNormal = 0,
		amtPatrolMove = 1,
		amtGroupPatrol = 2,
		amtGroupBoss = 3,
		amtGroupRamdom = 4,
		amtGroupInteractive = 5,
		amtBackoffMove = 6,
		amtCityPatrol = 7,
	}

	public enum KMailReturnCodeType
	{
		mrctSuccess = 0,
		mrctNotEnoughFreePackage = 1,
		mrctExpired = 2,
		mrctNotExisted = 3,
		mrctReceived = 4,
		mrctReceiving = 5,
	}

	public enum KMailReceiveStateType
	{
		mrstNotReceive = 0,
		mrstReceiving = 1,
		mrstReceived = 2,
	}

	public enum KBaseExDataKey
	{
		bekInvalid = 0,
		bekBodyAvatarID = 1,
		bekWeaponAvatarID = 2,
		bekWingID = 3,
		bekMantleID = 4,
		bekArtifactID = 5,
		bekAuraID = 6,
		bekArmor = 7,
		bekDragonSoul = 8,
		bekPlough = 9,
		bekMagicWeaponID = 10,
		bekCombat = 11,
		bekFashion = 12,
		bekYellowDiamond = 13,
		bekBlueDiamond = 14,
		bekVipLevel = 15,
		bekTotal = 16,
	}

	public enum KAIGroupType
	{
		agtIvalide = 0,
		agtBossRange = 1,
		agtRandom = 2,
		agtInteractive = 3,
		agtPatrol = 4,
		agtTotal = 5,
	}

	public enum KItemPoolType
	{
		iptHpPool = 1,
		iptMpPool = 2,
	}

	public enum KTitleConditionType
	{
		tctVipLevel = 1,
		tctHeroPartyRank = 2,
		tctFightRank = 3,
		tctOccupyCity = 4,
		tctDiamondLevel = 5,
		tctGoldCount = 6,
		tctCombatValue = 7,
		tctPlayerLevel = 8,
		tctRechargedGoldCount = 9,
		tctReceiveAchievement = 10,
		tctLevelRank = 11,
		tctGemRank = 12,
		tctHorseRank = 13,
		tctWingRank = 14,
		tctArtifactRank = 15,
		tctTalismanRank = 16,
		tctMantleRank = 17,
		tctAuraRank = 18,
		tctAmorRank = 19,
		tctDragonSoul = 20,
		tctPloughSoul = 21,
		tctActiveArtifactCount = 22,
		tctActiveTalismanCount = 23,
		tctActiveHorseCount = 24,
		tctActiveWingCount = 25,
		tctFirstRecharge = 26,
		tctFriendCount = 27,
		tctReceivedFlowerCount = 28,
		tctSentFlowerCount = 29,
		tctReceiveFlowerRank = 30,
		tctSendFlowerRank = 31,
		tctGuildFightRank = 32,
		tctEquipRank = 33,
		tctWuJiangRank = 34,
		tctHaveWuShenTeQuan = 35,
	}

	public enum KTitleOperatorType
	{
		totGreater = 1,
		totGreaterEqual = 2,
		totEqual = 3,
		totLessEqual = 4,
		totLess = 5,
	}

	public enum KTitleExistType
	{
		tetForever = 1,
		tetConditionLimit = 2,
		tetTimeLimit = 3,
	}

	public enum KTitleUpdateType
	{
		tutObtain = 1,
		tutUpdate = 2,
		tutLose = 3,
	}

	public enum KTitleErrorCodeType
	{
		tectSuccess = 0,
		tectNotObtained = 1,
		tectNotExist = 2,
	}

	public enum KCenterType
	{
		kctInvalid = 0,
		kctGameCenter = 1,
		kctZoneServer = 2,
	}

	public enum KSaveRoleDataTag
	{
		ksrdtDefault = 0,
		ksrdtSwitchGS = 1,
		ksrdtSwitchGC = 2,
		ksrdtSwitchZS = 3,
	}

	public enum KItemSource
	{
		itemSource_Default = 0,
		itemSource_XunBao = 1,
		ItemSource_PVE = 2,
		ItemSource_TeamPve = 3,
		ItemSource_ChallengePVE = 4,
		itemSource_GuardPVE = 5,
		itemSource_XZQJPVE = 6,
		itemSource_MoneyPve = 7,
		ItemSource_WorldMonsterPVE = 8,
		ItemSource_CityPatrol = 9,
		ItemSource_TreasureMap = 10,
		ItemSource_CompeteFam = 11,
		ItemSource_Max = 1000,
		ItemSource_Activity_Version_1 = 1001,
		ItemSource_Activity_Version_2 = 1002,
		ItemSource_Activity_Version_3 = 1003,
		ItemSource_Activity_Version_4 = 1004,
		ItemSource_Activity_Version_5 = 1005,
		ItemSource_Activity_Version_6 = 1006,
		ItemSource_Activity_Version_7 = 1007,
		ItemSource_Activity_Version_8 = 1008,
		ItemSource_Activity_Version_9 = 1009,
		ItemSource_Activity_Version_10 = 1010,
	}

	public enum KPlayerState
	{
		KState_Idle = 0,
		KState_WalkForward = 1,
		KState_RunForward = 2,
		KState_WalkBack = 3,
		KState_RunBack = 4,
		KState_Rotate = 5,
		KState_Jump = 6,
	}

	public enum MissionType
	{
		MissionDialog = 1,
		MissionKillMonster = 2,
		MissionExplore = 3,
		MissionItem = 4,
		MissionMadeShip = 5,
		MissionAddSkill = 6,
		MissionDungeonCompleted = 7,
		MissionShipCount = 8,
		MissionPlayerLevel = 9,
		MissionShipLevel = 10,
		MissionWeaponLevel = 11,
		MissionModLevel = 12,
		MissionModChange = 13,
		MissionProduct = 14,
		MissionPlayerDanLevel = 15,
		MissionWeaponChange = 16,
		MissionPower = 17,
		MissionTaskDone = 18,
	}

	public enum KErrorCode
	{
		errSwitchMapPlayerLimit = 0,
		errSwitchMapCountLimit = 1,
		errSwitchMapNoOpen = 2,
		errConfig = 3,
		errJumpMapNoIndex = 20,
		errJumpPosInvalid = 21,
		errJumpIsJumping = 22,
		errWithNoShip = 23,
		errPowerAlreadySet = 24,
		errPower = 25,
		errSendBlackMsg = 26,
		errSendNotOnLineMsg = 27,
		errSendHasTeamMsg = 28,
		errSendTeamInviteLimited = 29,
		errSendTeamInvited = 30,
		errSendTeamOnLineMsg = 31,
		errInviteTeamWithNoShip = 32,
		errInvitedTeamWithNoShip = 33,
		errTeamNumberMaxLimited = 34,
		errTeamOrganizedTimeLimited = 35,
		errTeamOrganizedLevelLimited = 36,
		errTeamOrganizedMapLimited = 37,
		errTeamOrganizedTeamNoticeError = 38,
		errTeamOrganizedTeamNoticeTimeError = 39,
		errTeamOrganizedTeamAlreadyError = 40,
		errTeamOrganizedAlready = 41,
		errTeamOrganizedDisAlready = 42,
		errTeamOrganizedLimitLeap = 43,
		errTeamOrganizedMemberLimitLeap = 44,
		errTeamOrganizedForbidInvatedMatching = 45,
		errTeamOrganizedForbidInvateMatching = 46,
		errTeamOrganizedForbidInvated = 47,
		errTeamOrganizedForbidCreateTeam = 48,
		errTeamOrganizedNotHadAirShip = 49,
		errTeamOrganizedMemberNotHadAirShip = 50,
		errTeamPriForLeaderAsMatch = 51,
		errTeamInviteInSence = 52,
		errPackageNumForLimited = 53,
		errPackageAddForMoneyLimited = 54,
		errPackageMaxNumForLimited = 55,
		errPackageMaxStackForLimited = 56,
		errPackageWeaponForDisbind = 57,
		errPackageModForDisbind = 58,
		errLastShipForDisbind = 59,
		errShipTIDForActive = 60,
		errMaterialForActive = 61,
		errCancleMagazine = 62,
		errJumpNotJumping = 63,
		errJumpUnVisible = 64,
		errHeroIsDead = 65,
		errLeapingOrTimeLock = 66,
		errHeroNotDead = 67,
		errReliveCDLimit = 68,
		errReliveWrongMap = 69,
		errNoValidRelivePos = 70,
		errNotInGroundScene = 71,
	}

	public enum FightStatus
	{
		NotFighting = 0,
		Fighting = 1,
	}

	public enum KWeaponType
	{
		None = 0,
		Turret = 1,
		Missile = 2,
		UAV = 3,
		Howitzer = 4,
		Laser = 5,
		Guard = 6,
		Support = 7,
	}

	public enum KWeaponPos
	{
		ShipSelf = 0,
		Main = 1,
		Sub = 2,
		Super = 3,
		Furnace = 4,
		UNKNOWN = 5,
	}

	public enum KGlobalKey
	{
		CommonTime1 = 100,
		CommonTime2 = 101,
		CommonTime3 = 102,
		DockShipMaxCount = 1000,
		ProductMaxCount = 1001,
		FoundryOneMinPirce = 2000,
		SharedViewDistance = 2001,
		TeamOrganizedTimeLimited = 2002,
		MatchMaxDownTime = 3001,
		MatchMaxUpTime = 3002,
		ExtendMatchingTime = 3003,
		MatchTeamMemberCount = 3004,
		MatchTeamTimeLimited = 3005,
		PackageNumForBegin = 3006,
		PackagePosPrice = 3007,
		PackagePosPriceAdd = 3008,
		PackageMaxPosLimited = 3009,
		PackageMaxPosDayTaskLimited = 3010,
		HateSysEnterView = 3011,
		HateSysDamaged = 3012,
		HateSysSwitchTargetCD = 3013,
		ReliveCDTime = 3014,
		SpacecraftFarClipRange = 4001,
		CharacterFarClipRange = 4002,
		AddRateForPole = 10000,
		AddRateForNegativePole = 10001,
		DisRateForPole = 10002,
		DisRateForNegativePole = 10003,
		DilatationForWarShip = 10004,
		DilatationForWeapon = 10005,
		DilatationForWarShipNum = 10006,
		DilatationForWeaponNum = 10007,
		ContainerForWarship = 10008,
		ContainerForWeapon = 10009,
		PackageNumBeginForShip = 10020,
		PackageNumMaxForShip = 10021,
		PackagePosPriceForShip = 10022,
		PackageNumBeginForWeapon = 10023,
		PackageNumMaxForWeapon = 10024,
		PackagePosPriceForWeapon = 10025,
		PackageNumBeginForMetail = 10026,
		PackageNumMaxForMetail = 10027,
		PackagePosPriceForMetail = 10028,
		PackageNumBeginForBlue = 10029,
		PackageNumMaxForBlue = 10030,
		PackagePosPriceForBlue = 10031,
		PackageNumBeginForMod = 10032,
		PackageNumMaxForMod = 10033,
		PackagePosPriceForMod = 10034,
		MaximumStableProgress = 10035,
		MaximumAccuracyProgress = 10036,
		MaximumRangeProgress = 10037,
		TemporaryGroupID = 200001,
		MialMaxPosLimited = 300001,
		WorldMissionTimeRate = 600001,
		WorldMissionHurtRate = 600002,
		TutorialBlewWhenCompleteMissionId = 600003,
		TutorialBlewWhenOwnSpacecraftId = 600004,
		BehavicNPCSpecialID = 700001,
		BehavicEnergyBuffID = 700002,
		BehavicNPCSpecialSkillID = 700003,
		BehavicPlayerSpecialID = 700004,
		BehavicPlayerExtractBuffID = 700005,
		BehavicDetectorExtractBuffID = 700006,
	}

	public enum KGlobalColorKey
	{
		Quality1 = 1,
		Quality2 = 2,
		Quality3 = 3,
		Quality4 = 4,
		Quality5 = 5,
		Quality6 = 6,
		Quality7 = 7,
		Mission1 = 101,
		Mission2 = 102,
		Mission3 = 103,
		SliderBlue = 202,
		SliderRed = 203,
		SliderGray = 204,
		SliderYellow = 205,
		GeneralNotice = 301,
		ErrorNotice = 302,
		TextColor1 = 1001,
		TextColor2 = 1002,
		TextColor3 = 1003,
		TextColor4 = 1004,
		ModLevelDisable = 2001,
	}

	public enum KPowerType
	{
		NonePower = 0,
		RepublicOfEyre = 1,
		HolyAreaOfTheVaticanHeim = 2,
		HeartAllianceOfHighPlatinum = 3,
	}

	public enum WeaponMainType
	{
		HideType = 0,
		MainType = 1,
		SubType = 2,
		SupperType = 3,
		Reformer = 4,
	}

	public enum WeaponTypeD
	{
		ArtilleryD = 1,
		MissileD = 2,
		LaserD = 5,
		GrenadeD = 4,
		UAVD = 3,
		GuardD = 6,
		SupportD = 7,
	}

	public enum WeaponSubType
	{
		Gatlin = 101,
		Canon = 102,
		TacticsMissile = 201,
		Rocket = 202,
		Torpedo = 203,
		TacticsLaser = 501,
		Pulse = 502,
		Plasma = 503,
		TacticsGrenade = 401,
		ArmedUAV = 301,
		BurstUAV = 302,
		Mine = 303,
	}

	public enum ClipType
	{
		BulletClip = 1,
		MagazineClip = 2,
		HeatClip = 3,
	}

	public enum CastSpellCode
	{
		suc = 0,
		cding = 1,
		singing = 2,
		mutiling = 3,
		targeter_error = 4,
		energy_not_enough = 5,
		spell_config_error = 6,
		out_range = 7,
		caster_die = 8,
		targeter_die = 9,
		begin_sing = 10,
		begin_mulspell = 11,
		failed = 12,
		spell_not_exist = 13,
		not_use_airship = 14,
		weapon_value_not_enuough = 15,
		cruise_status_not_cast = 16,
	}

	public enum KMailErrorCode
	{
		KMailSuccess = 0,
		KMailWrongGroupType = 1,
		KMailGroupAlreadyIn = 3,
		KMailCardNotExist = 4,
		KMailPageNotExist = 5,
		KMailMailGroupNotExist = 7,
		KMailMailCardNotInGroup = 8,
		KMailNotExist = 10,
		KMailItemTokenError = 11,
		KMailItemGot = 12,
		KMailItemExpireData = 13,
		KMailWrongMailType = 14,
		KMailRecevierNotExist = 15,
		KMailDeleteErrorImportant = 16,
		KMailDeleteErrorAccessory = 17,
		KMailPlayerBagNotEnough = 1001,
	}

	public enum BuffEffectType
	{
		RecoveHPRate = 1,
		AddSpellAttr = 2,
		RecoverShieldRate = 3,
		MinusSpellCost = 4,
		Dot = 5,
		AddAttribute = 6,
		Invisible = 7,
		CastSkill = 9,
		RecoverPowerRate = 10,
		CounterattackInjury = 11,
		LinkDamage = 12,
		AddTrigger = 13,
		LinkStatus = 14,
		ChangeSkillItem = 15,
	}

	public enum GroupRuleId
	{
		Mutually = 1,
		Stacking = 2,
		LastTrigger = 3,
		Paralleling = 4,
	}

	public enum AbnormalState
	{
		NoneAbnormal = 0,
		Decelera = 1,
		Burning = 2,
		Imprison = 3,
		Silence = 4,
		Dizz = 5,
	}

	public enum PassiveEffectType
	{
		AddBuf = 1,
		MinusSpellCd = 2,
		AddSpellHeat = 3,
		AddBufHeat = 4,
		ImmunoBuf = 5,
		AddBufTime = 6,
		ChangeBufEffect = 7,
	}

	public enum WildNPCFightState
	{
		Finding = 1,
		FollowUp = 2,
		Attacking = 3,
		Returning = 4,
	}

	public enum NpcTriggerState
	{
		Firststate = 10000,
		Secondstate = 20000,
		Thirdstate = 30000,
	}

	public enum NpcTriggerCondition
	{
		DoNothing = 0,
		AcceptBehaviacThree = 1,
		EnterTriggerView = 2,
		SpecialNpcDie = 3,
		NoEmerny = 4,
		PlayerEnter = 5,
		PlayerLeave = 6,
		PlayerEnterPreicousSignal = 7,
		PlayerEnterPreicous = 8,
		PlayerEnterRedBuff = 9,
		PlayerEnterBlueBuff = 10,
		MissionConvoyNpcEnter = 11,
		MissionRangeOutNpc = 12,
		NpcTriggerConditionMax = 13,
	}

	public enum NpcTriggerEvent
	{
		FreshNpcList = 100,
		ResetNpcList = 200,
		SendNpcToScene = 300,
		BeginFight = 400,
		ChangeState = 500,
		ExecuteState = 600,
		ExecuteBuff = 700,
		FinishMission = 800,
		OutSunmmRange = 900,
		ClearMineDrop = 1000,
		PlayerDiscoverSignal = 1100,
		PlayerDiscoverPreicous = 1200,
	}

	public enum NpcDieType
	{
		NormalDie = 1,
		DieNature = 2,
		LiveTimeEnd = 3,
	}

	public enum DetectPlayMethodValue
	{
		ExtractDis = 1500,
		EnergyCurValue = 20,
		InitEnergyValue = 20,
		EnergyMaxValue = 100,
		TriggerMaxTime = 100,
		RandomMoveMin = 700,
		RandomMoveMax = 1000,
		RandomMoveStopTIme = 2000,
		MinDisFromEnery = 2000,
		ForwardStopTime = 2000,
		RandomForwardMin = 3000,
		RandomForwardMax = 4000,
		DistanceFromEnemy = 1000,
		RandomXZPro = 30,
		RandomXZForwardTime = 1500,
		RandomXZRestTime = 3000,
	}

	public enum BattleStatus
	{
		BATTLE_DiSAPPEAR = 0,
		BATTLE_BEGIN = 1,
		BATTLE_PRETIME = 2,
		BATTLE_ACTIVE = 3,
		BATTLE_END_CD = 4,
	}

	public enum CampRelation
	{
		Enemy = 0,
		Neutrality = 1,
		Friend = 2,
		Undefined = 3,
	}

	public enum MissionGenre
	{
		MissionGenreUndefined = 0,
		MainMission = 1,
		SideMission = 2,
		DailyMission = 3,
		RaidMission = 4,
		WorldMission = 5,
	}

	public enum MissionState
	{
		CanAccept = 1,
		Processing = 2,
		Complete = 3,
	}

	public enum GuidStepNum
	{
		ShipTid = 1,
		SenceTid = 2,
		BirthPos = 3,
		BirthDir = 4,
		BirthTaskTid = 5,
		BirthMailTid = 6,
		BirthAreaId = 7,
	}

	public enum ChestType
	{
		BattleFieldChest = 1,
		LootChest = 2,
		MapNpcChest = 3,
	}

	public enum ChestResultErrorCode
	{
		ChestResultSuccess = 0,
		ChestResultUnKnownError = 1,
		ChestNotExist = 2,
	}

	public enum WorldEventState
	{
		WorldEventPrepare = 0,
		WorldEventActive = 1,
		WorldEventTriggerTime = 2,
		WorldEventCD = 3,
	}

	public enum ForceActionType
	{
		ActionTypeToIdle = 0,
		ActionTypeTurnToTarget = 1,
		ActionTypeStopRotate = 2,
		ActionTypeStopMove = 3,
		ActionTypeMoveToTarget = 4,
		ActionTypeSmoothMoveToTarget = 5,
	}

	public enum ItemOperateType
	{
		IOTAddItem = 0,
		IOTDestoryItem = 1,
		IOTConsumeItem = 2,
		IOTMoveItem = 3,
		IOTIncreaseCapcity = 4,
		IOTSplitItem = 5,
		IOTSkillChanged = 6,
	}

	public enum ItemOperateErrorCode
	{
		IOECSuccess = 0,
		IOECUnkownError = 1,
		IOECNotExistThisItem = 2,
		IOECInvalidPosition = 3,
		IOECInvalidItemType = 4,
		IOECInvalidStorage = 5,
		IOECNotEnoughItems = 6,
		IOECContainerAddItemNotEnoughSpace = 7,
		IOECContainerIncreaseCapacityOverMax = 8,
		IOECNotMatchThisContainer = 9,
		IOECContainerNotExist = 10,
		IOECContainerMergeDestStackOver = 11,
		IOECMoveItemInvalidSrc = 12,
		IOECMoveItemInvalidDest = 13,
		IOECMoveItemButLock = 14,
		IOECPickUpItemError = 15,
		IOECMergeRemoveItemError = 16,
		IOECSplitStackCountError = 17,
		IOECSplitRemoveItemError = 18,
		IOECInertItemPosItemNotMatch = 19,
		IOECMergeContainerSourceEmpty = 20,
		IOECMergeContainerDestinationFull = 21,
		IOECNotNewItem = 22,
		IOECInsertRuleFailed = 23,
		IOECMergeNotSameType = 24,
	}

	public enum ItemProcessType
	{
		IPTAddItem = 0,
		IPTDeleteItem = 1,
		IPTStackChange = 2,
		IPTPositionChange = 3,
		IPTCapacityChange = 4,
		IPTSizeChange = 5,
	}

	public enum MailParamType
	{
		MPTTitle = 0,
		MPTContent = 1,
		MPTSender = 2,
	}

	public enum MailParamTargetType
	{
		MPTString = 0,
		MPTTTask = 1,
	}

	public enum ItemDisplayLogErrorCode
	{
		IDLECSuccess = 0,
		IDLECUnknown = 1,
	}

	public enum ClientResetType
	{
		ResetSelf = 0,
		ResetAll = 1,
	}

	public enum AIPlotState
	{
		Idle = 0,
		Invaded = 1,
		LostPlayer = 2,
		MonsterRetreat = 3,
		MonsterRetreatFail = 4,
		BeginCallingBoss = 5,
		CallingBossSuccess = 6,
		CallingBossFail = 7,
		BeginBossTimeout = 8,
		BossTimeout = 9,
		DefeatBoss = 10,
		PlayerOutOfScene = 11,
		Invaded2 = 12,
		CloseInvaded2 = 13,
	}

	public enum SoundID
	{
		LoadUp = 1002,
		LoadDown = 1003,
		LoadEnd = 1004,
		CombatWranOpen = 1008,
		CombatWranEnd = 1009,
		CombatOpen = 1010,
		CombatEnd = 1011,
		AIAreaWran = 1012,
		AIAreaCombat = 1013,
		AIAreaMonsterRetreat = 1014,
		AIAreaCallingBossSuccess = 1015,
		AIAreaBeginBossTimeout = 1016,
		AIAreaDefeatBoss = 1017,
		AIAreaEnd = 1018,
		AIAreaEvent = 1019,
	}

	public enum PlayerDiscoverPreciousType
	{
		DiscoverSignal = 0,
		DiscoverPrecious = 1,
	}

	public enum SceneState
	{
		SSNone = 0,
	}

	public enum TreasureSpawnType
	{
		TstNormalChest = 1,
		TstLockChest = 2,
		TstNormalMonster = 3,
		TstRareMonster = 4,
	}

}
